// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("doppler");

/**
 * A Doppler token, either a personal or service token. This can also be set via the DOPPLER_TOKEN environment variable. Only one of `dopplerToken` or OIDC authentication (`oidcIdentity` + `oidcToken`/`oidcTokenFile`) may be specified.
 */
export declare const dopplerToken: string | undefined;
Object.defineProperty(exports, "dopplerToken", {
    get() {
        return __config.get("dopplerToken") ?? utilities.getEnv("DOPPLER_TOKEN");
    },
    enumerable: true,
});

/**
 * The Doppler API host (i.e. https://api.doppler.com). This can also be set via the DOPPLER_API_HOST environment variable.
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host") ?? utilities.getEnv("DOPPLER_API_HOST");
    },
    enumerable: true,
});

/**
 * The identity ID (UUID) of the Doppler service account identity for OIDC authentication. This can also be set via the DOPPLER_OIDC_IDENTITY environment variable.
 */
export declare const oidcIdentity: string | undefined;
Object.defineProperty(exports, "oidcIdentity", {
    get() {
        return __config.get("oidcIdentity");
    },
    enumerable: true,
});

/**
 * A JWT token to use for OIDC authentication. Only one of `oidcToken` or `oidcTokenFile` may be set. This can also be set via the DOPPLER_OIDC_TOKEN environment variable.
 */
export declare const oidcToken: string | undefined;
Object.defineProperty(exports, "oidcToken", {
    get() {
        return __config.get("oidcToken");
    },
    enumerable: true,
});

/**
 * A path to a file containing a JWT token for OIDC authentication (e.g. a Kubernetes projected service account token). Only one of `oidcToken` or `oidcTokenFile` may be set. This can also be set via the DOPPLER_OIDC_TOKEN_FILE environment variable.
 */
export declare const oidcTokenFile: string | undefined;
Object.defineProperty(exports, "oidcTokenFile", {
    get() {
        return __config.get("oidcTokenFile");
    },
    enumerable: true,
});

/**
 * Whether or not to verify TLS. This can also be set via the DOPPLER_VERIFY_TLS environment variable.
 */
export declare const verifyTls: boolean | undefined;
Object.defineProperty(exports, "verifyTls", {
    get() {
        return __config.getObject<boolean>("verifyTls") ?? utilities.getEnvBoolean("DOPPLER_VERIFY_TLS");
    },
    enumerable: true,
});

