// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ChangeRequestPolicyRules {
    /**
     * If set, the strategy used to automatically assign reviewers to CRs targeted by this policy. Valid values: all, matchCount, never (default)
     */
    autoAssignReviewers?: pulumi.Input<string | undefined>;
    /**
     * If true, approvals from the author of a change request will be excluded when evaluating this policy
     */
    disallowSelfReview?: pulumi.Input<boolean | undefined>;
    /**
     * Enforces that a specific number of users approve a change request before it can be applied
     */
    requiredReviewers?: pulumi.Input<pulumi.Input<inputs.ChangeRequestPolicyRulesRequiredReviewer>[] | undefined>;
}

export interface ChangeRequestPolicyRulesRequiredReviewer {
    /**
     * The number of approvals a change request must receive before it can be applied
     */
    count: pulumi.Input<number>;
    /**
     * If set, only approvals from members of these groups will satisfy this rule
     */
    groupSlugs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * If set, only approvals from these users will satisfy this rule
     */
    userSlugs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface ChangeRequestPolicyTargets {
    /**
     * Whether or not the policy applies to all projects in the workplace
     */
    allProjects?: pulumi.Input<boolean | undefined>;
    /**
     * A project that the policy will apply to
     */
    projects?: pulumi.Input<pulumi.Input<inputs.ChangeRequestPolicyTargetsProject>[] | undefined>;
}

export interface ChangeRequestPolicyTargetsProject {
    /**
     * Whether or not the policy applies to all configs in the project
     */
    all?: pulumi.Input<boolean | undefined>;
    /**
     * Specific configs the policy applies to
     */
    configNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Entire environments the policy applies to
     */
    environmentSlugs?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name of the project to apply the policy to
     */
    projectName: pulumi.Input<string>;
}

export interface RotatedSecretAwsMssqlCredential {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}

export interface RotatedSecretAwsMysqlCredential {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}

export interface RotatedSecretAwsPostgresCredential {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}

export interface RotatedSecretCloudflareTokensCredential {
    value: pulumi.Input<string>;
}

export interface RotatedSecretGcpCloudsqlCredential {
    password: pulumi.Input<string>;
    userHostName?: pulumi.Input<string | undefined>;
    username: pulumi.Input<string>;
}

export interface RotatedSecretMongodbAtlasCredential {
    password: pulumi.Input<string>;
    username: pulumi.Input<string>;
}

export interface ServiceAccountIdentityConfigOidc {
    /**
     * A set of valid values for a specific claim. At least "aud" and "sub" must be provided
     */
    claims: pulumi.Input<pulumi.Input<inputs.ServiceAccountIdentityConfigOidcClaim>[]>;
    /**
     * If "wildcard", wildcard characters will be expanded during claims validation. Defaults to "exact"
     */
    claimsType?: pulumi.Input<string | undefined>;
    /**
     * The public URL of the OpenID discovery service
     */
    discoveryUrl: pulumi.Input<string>;
}

export interface ServiceAccountIdentityConfigOidcClaim {
    /**
     * The key of the claim to validate
     */
    key: pulumi.Input<string>;
    /**
     * The set of valid values for this claim
     */
    values: pulumi.Input<pulumi.Input<string>[]>;
}

export interface WebhookAuthentication {
    password?: pulumi.Input<string | undefined>;
    token?: pulumi.Input<string | undefined>;
    type: pulumi.Input<string>;
    username?: pulumi.Input<string | undefined>;
}
