// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ChangeRequestPolicyRules {
    /**
     * If set, the strategy used to automatically assign reviewers to CRs targeted by this policy. Valid values: all, matchCount, never (default)
     */
    autoAssignReviewers?: string;
    /**
     * If true, approvals from the author of a change request will be excluded when evaluating this policy
     */
    disallowSelfReview?: boolean;
    /**
     * Enforces that a specific number of users approve a change request before it can be applied
     */
    requiredReviewers?: outputs.ChangeRequestPolicyRulesRequiredReviewer[];
}

export interface ChangeRequestPolicyRulesRequiredReviewer {
    /**
     * The number of approvals a change request must receive before it can be applied
     */
    count: number;
    /**
     * If set, only approvals from members of these groups will satisfy this rule
     */
    groupSlugs?: string[];
    /**
     * If set, only approvals from these users will satisfy this rule
     */
    userSlugs?: string[];
}

export interface ChangeRequestPolicyTargets {
    /**
     * Whether or not the policy applies to all projects in the workplace
     */
    allProjects?: boolean;
    /**
     * A project that the policy will apply to
     */
    projects?: outputs.ChangeRequestPolicyTargetsProject[];
}

export interface ChangeRequestPolicyTargetsProject {
    /**
     * Whether or not the policy applies to all configs in the project
     */
    all?: boolean;
    /**
     * Specific configs the policy applies to
     */
    configNames?: string[];
    /**
     * Entire environments the policy applies to
     */
    environmentSlugs?: string[];
    /**
     * The name of the project to apply the policy to
     */
    projectName: string;
}

export interface GetEnvironmentsList {
    /**
     * When the environment was created
     */
    createdAt: string;
    /**
     * The name of the environment
     */
    name: string;
    /**
     * The project the environment belongs to
     */
    project: string;
    /**
     * The slug of the environment
     */
    slug: string;
}

export interface RotatedSecretAwsMssqlCredential {
    password: string;
    username: string;
}

export interface RotatedSecretAwsMysqlCredential {
    password: string;
    username: string;
}

export interface RotatedSecretAwsPostgresCredential {
    password: string;
    username: string;
}

export interface RotatedSecretCloudflareTokensCredential {
    value: string;
}

export interface RotatedSecretGcpCloudsqlCredential {
    password: string;
    userHostName?: string;
    username: string;
}

export interface RotatedSecretMongodbAtlasCredential {
    password: string;
    username: string;
}

export interface ServiceAccountIdentityConfigOidc {
    /**
     * A set of valid values for a specific claim. At least "aud" and "sub" must be provided
     */
    claims: outputs.ServiceAccountIdentityConfigOidcClaim[];
    /**
     * If "wildcard", wildcard characters will be expanded during claims validation. Defaults to "exact"
     */
    claimsType?: string;
    /**
     * The public URL of the OpenID discovery service
     */
    discoveryUrl: string;
}

export interface ServiceAccountIdentityConfigOidcClaim {
    /**
     * The key of the claim to validate
     */
    key: string;
    /**
     * The set of valid values for this claim
     */
    values: string[];
}

export interface WebhookAuthentication {
    password?: string;
    token?: string;
    type: string;
    username?: string;
}

