// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manage a Doppler change request policy.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 * import * as std from "@pulumi/std";
 *
 * export = async () => {
 *     const nic = await doppler.getUser({
 *         email: "nic@doppler.com",
 *     });
 *     const emily = await doppler.getUser({
 *         email: "emily@doppler.com",
 *     });
 *     const testProj = new doppler.Project("test_proj", {
 *         name: "my-test-project",
 *         description: "This is a test project",
 *     });
 *     const prd = new doppler.Environment("prd", {
 *         project: testProj.name,
 *         slug: "prd",
 *         name: "prd",
 *     });
 *     const ci = new doppler.Environment("ci", {
 *         project: testProj.name,
 *         slug: "ci",
 *         name: "CI-CD",
 *     });
 *     const ciGithub = new doppler.Config("ci_github", {
 *         project: testProj.name,
 *         environment: ci.slug,
 *         name: "ci_github",
 *     });
 *     const prodReviewers = new doppler.Group("prod_reviewers", {name: "Prod Reviewers"});
 *     const prodReviewersGroupMember: doppler.GroupMember[] = [];
 *     for (const range of std.toset({
 *         input: [nic.slug],
 *     }).result.map((v, k) => ({key: k, value: v}))) {
 *         prodReviewersGroupMember.push(new doppler.GroupMember(`prod_reviewers-${range.key}`, {
 *             groupSlug: prodReviewers.slug,
 *             userSlug: range.value,
 *         }));
 *     }
 *     const prdReview = new doppler.ChangeRequestPolicy("prd_review", {
 *         name: "Prod Review",
 *         description: `A change request policy which requires 2 total approvals, and 1 approval from emily or any member of the prod_reviewers group.
 * Reviews from the author of the change request are not counted.
 * This policy is enforced in all configs of the prd environment of test_proj, as well as the ci_github branch config.
 * `,
 *         rules: {
 *             disallowSelfReview: true,
 *             autoAssignReviewers: "matchCount",
 *             requiredReviewers: [
 *                 {
 *                     count: 2,
 *                 },
 *                 {
 *                     count: 1,
 *                     groupSlugs: [prodReviewers.slug],
 *                     userSlugs: [emily.slug],
 *                 },
 *             ],
 *         },
 *         targets: {
 *             projects: [{
 *                 projectName: testProj.name,
 *                 environmentSlugs: [prd.slug],
 *                 configNames: [ciGithub.name],
 *             }],
 *         },
 *     });
 * }
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import doppler:index/changeRequestPolicy:ChangeRequestPolicy <name> <change-request-policy-id>
 * ```
 */
export class ChangeRequestPolicy extends pulumi.CustomResource {
    /**
     * Get an existing ChangeRequestPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ChangeRequestPolicyState, opts?: pulumi.CustomResourceOptions): ChangeRequestPolicy {
        return new ChangeRequestPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/changeRequestPolicy:ChangeRequestPolicy';

    /**
     * Returns true if the given object is an instance of ChangeRequestPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ChangeRequestPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ChangeRequestPolicy.__pulumiType;
    }

    /**
     * A description of the change request policy
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The name of the change request policy
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Rules that the policy will apply to its targets
     */
    declare public readonly rules: pulumi.Output<outputs.ChangeRequestPolicyRules>;
    /**
     * The unique identifier of the change request policy
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;
    /**
     * Where the policy will apply
     */
    declare public readonly targets: pulumi.Output<outputs.ChangeRequestPolicyTargets>;

    /**
     * Create a ChangeRequestPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ChangeRequestPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ChangeRequestPolicyArgs | ChangeRequestPolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ChangeRequestPolicyState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["rules"] = state?.rules;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["targets"] = state?.targets;
        } else {
            const args = argsOrState as ChangeRequestPolicyArgs | undefined;
            if (args?.rules === undefined && !opts.urn) {
                throw new Error("Missing required property 'rules'");
            }
            if (args?.targets === undefined && !opts.urn) {
                throw new Error("Missing required property 'targets'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["rules"] = args?.rules;
            resourceInputs["targets"] = args?.targets;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ChangeRequestPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ChangeRequestPolicy resources.
 */
export interface ChangeRequestPolicyState {
    /**
     * A description of the change request policy
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The name of the change request policy
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Rules that the policy will apply to its targets
     */
    rules?: pulumi.Input<inputs.ChangeRequestPolicyRules | undefined>;
    /**
     * The unique identifier of the change request policy
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * Where the policy will apply
     */
    targets?: pulumi.Input<inputs.ChangeRequestPolicyTargets | undefined>;
}

/**
 * The set of arguments for constructing a ChangeRequestPolicy resource.
 */
export interface ChangeRequestPolicyArgs {
    /**
     * A description of the change request policy
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The name of the change request policy
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Rules that the policy will apply to its targets
     */
    rules: pulumi.Input<inputs.ChangeRequestPolicyRules>;
    /**
     * Where the policy will apply
     */
    targets: pulumi.Input<inputs.ChangeRequestPolicyTargets>;
}
