// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Doppler config.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const backendCiGithub = new doppler.Config("backend_ci_github", {
 *     project: "backend",
 *     environment: "ci",
 *     name: "ci_github",
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import doppler:index/config:Config default <project-name>.<environment-slug>.<config-name>
 * ```
 */
export class Config extends pulumi.CustomResource {
    /**
     * Get an existing Config resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConfigState, opts?: pulumi.CustomResourceOptions): Config {
        return new Config(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/config:Config';

    /**
     * Returns true if the given object is an instance of Config.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Config {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Config.__pulumiType;
    }

    /**
     * The descriptor (project.config) of the Doppler config
     */
    declare public /*out*/ readonly descriptor: pulumi.Output<string>;
    /**
     * The name of the Doppler environment where the config is located
     */
    declare public readonly environment: pulumi.Output<string>;
    /**
     * Whether or not the Doppler config can be inherited by other configs
     */
    declare public readonly inheritable: pulumi.Output<boolean | undefined>;
    /**
     * A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler*config resource (e.g. doppler*config.backend_stg.descriptor)
     */
    declare public readonly inherits: pulumi.Output<string[] | undefined>;
    /**
     * The name of the Doppler config
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The name of the Doppler project where the config is located
     */
    declare public readonly project: pulumi.Output<string>;

    /**
     * Create a Config resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConfigArgs | ConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConfigState | undefined;
            resourceInputs["descriptor"] = state?.descriptor;
            resourceInputs["environment"] = state?.environment;
            resourceInputs["inheritable"] = state?.inheritable;
            resourceInputs["inherits"] = state?.inherits;
            resourceInputs["name"] = state?.name;
            resourceInputs["project"] = state?.project;
        } else {
            const args = argsOrState as ConfigArgs | undefined;
            if (args?.environment === undefined && !opts.urn) {
                throw new Error("Missing required property 'environment'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            resourceInputs["environment"] = args?.environment;
            resourceInputs["inheritable"] = args?.inheritable;
            resourceInputs["inherits"] = args?.inherits;
            resourceInputs["name"] = args?.name;
            resourceInputs["project"] = args?.project;
            resourceInputs["descriptor"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Config.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Config resources.
 */
export interface ConfigState {
    /**
     * The descriptor (project.config) of the Doppler config
     */
    descriptor?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler environment where the config is located
     */
    environment?: pulumi.Input<string | undefined>;
    /**
     * Whether or not the Doppler config can be inherited by other configs
     */
    inheritable?: pulumi.Input<boolean | undefined>;
    /**
     * A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler*config resource (e.g. doppler*config.backend_stg.descriptor)
     */
    inherits?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name of the Doppler config
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project where the config is located
     */
    project?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Config resource.
 */
export interface ConfigArgs {
    /**
     * The name of the Doppler environment where the config is located
     */
    environment: pulumi.Input<string>;
    /**
     * Whether or not the Doppler config can be inherited by other configs
     */
    inheritable?: pulumi.Input<boolean | undefined>;
    /**
     * A list of other Doppler config descriptors that this config inherits from. Descriptors match the format "project.config" (e.g. backend.stg), which is most easily retrieved as the computed descriptor of a doppler*config resource (e.g. doppler*config.backend_stg.descriptor)
     */
    inherits?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name of the Doppler config
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project where the config is located
     */
    project: pulumi.Input<string>;
}
