// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Retrieve all environments in the project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const all = doppler.getEnvironments({
 *     project: "my-project",
 * });
 * export const environmentNames = all.then(all => .map(env => (env.name)));
 * export const environmentSlugs = all.then(all => .map(env => (env.slug)));
 * ```
 */
export function getEnvironments(args: GetEnvironmentsArgs, opts?: pulumi.InvokeOptions): Promise<GetEnvironmentsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("doppler:index/getEnvironments:getEnvironments", {
        "project": args.project,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvironments.
 */
export interface GetEnvironmentsArgs {
    /**
     * The project to list environments for
     */
    project: string;
}

/**
 * A collection of values returned by getEnvironments.
 */
export interface GetEnvironmentsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of environments in the project
     */
    readonly lists: outputs.GetEnvironmentsList[];
    /**
     * The project to list environments for
     */
    readonly project: string;
}
/**
 * Retrieve all environments in the project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const all = doppler.getEnvironments({
 *     project: "my-project",
 * });
 * export const environmentNames = all.then(all => .map(env => (env.name)));
 * export const environmentSlugs = all.then(all => .map(env => (env.slug)));
 * ```
 */
export function getEnvironmentsOutput(args: GetEnvironmentsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnvironmentsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("doppler:index/getEnvironments:getEnvironments", {
        "project": args.project,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnvironments.
 */
export interface GetEnvironmentsOutputArgs {
    /**
     * The project to list environments for
     */
    project: pulumi.Input<string>;
}
