// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Doppler group.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const engineering = new doppler.Group("engineering", {
 *     name: "engineering",
 *     workplaceRole: "viewer",
 * });
 * ```
 *
 * ## Import
 *
 * import using the group slug from the URL:
 * https://dashboard.doppler.com/workplace/[workplace-slug]/team/groups/[group-slug]
 *
 * ```sh
 * $ pulumi import doppler:index/group:Group default <group-slug>
 * ```
 */
export class Group extends pulumi.CustomResource {
    /**
     * Get an existing Group resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupState, opts?: pulumi.CustomResourceOptions): Group {
        return new Group(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/group:Group';

    /**
     * Returns true if the given object is an instance of Group.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Group {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Group.__pulumiType;
    }

    /**
     * The default project role assigned to the group when added to a Doppler project. If set to null, the default project role is inherited from the workplace setting.
     */
    declare public readonly defaultProjectRole: pulumi.Output<string | undefined>;
    /**
     * The name of the group
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The slug of the group
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;
    /**
     * The workplace role assigned to members of the group. If omitted, state will be tracked in Terraform but not updated in Doppler. Use "noAccess" to ensure the group has no workplace permissions
     */
    declare public readonly workplaceRole: pulumi.Output<string | undefined>;

    /**
     * Create a Group resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupArgs | GroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupState | undefined;
            resourceInputs["defaultProjectRole"] = state?.defaultProjectRole;
            resourceInputs["name"] = state?.name;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["workplaceRole"] = state?.workplaceRole;
        } else {
            const args = argsOrState as GroupArgs | undefined;
            resourceInputs["defaultProjectRole"] = args?.defaultProjectRole;
            resourceInputs["name"] = args?.name;
            resourceInputs["workplaceRole"] = args?.workplaceRole;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Group.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Group resources.
 */
export interface GroupState {
    /**
     * The default project role assigned to the group when added to a Doppler project. If set to null, the default project role is inherited from the workplace setting.
     */
    defaultProjectRole?: pulumi.Input<string | undefined>;
    /**
     * The name of the group
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The slug of the group
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * The workplace role assigned to members of the group. If omitted, state will be tracked in Terraform but not updated in Doppler. Use "noAccess" to ensure the group has no workplace permissions
     */
    workplaceRole?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Group resource.
 */
export interface GroupArgs {
    /**
     * The default project role assigned to the group when added to a Doppler project. If set to null, the default project role is inherited from the workplace setting.
     */
    defaultProjectRole?: pulumi.Input<string | undefined>;
    /**
     * The name of the group
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The workplace role assigned to members of the group. If omitted, state will be tracked in Terraform but not updated in Doppler. Use "noAccess" to ensure the group has no workplace permissions
     */
    workplaceRole?: pulumi.Input<string | undefined>;
}
