// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ChangeRequestPolicyArgs, ChangeRequestPolicyState } from "./changeRequestPolicy";
export type ChangeRequestPolicy = import("./changeRequestPolicy").ChangeRequestPolicy;
export const ChangeRequestPolicy: typeof import("./changeRequestPolicy").ChangeRequestPolicy = null as any;
utilities.lazyLoad(exports, ["ChangeRequestPolicy"], () => require("./changeRequestPolicy"));

export { ConfigArgs, ConfigState } from "./config_";
export type Config = import("./config_").Config;
export const Config: typeof import("./config_").Config = null as any;
utilities.lazyLoad(exports, ["Config"], () => require("./config_"));

export { EnvironmentArgs, EnvironmentState } from "./environment";
export type Environment = import("./environment").Environment;
export const Environment: typeof import("./environment").Environment = null as any;
utilities.lazyLoad(exports, ["Environment"], () => require("./environment"));

export { GetEnvironmentsArgs, GetEnvironmentsResult, GetEnvironmentsOutputArgs } from "./getEnvironments";
export const getEnvironments: typeof import("./getEnvironments").getEnvironments = null as any;
export const getEnvironmentsOutput: typeof import("./getEnvironments").getEnvironmentsOutput = null as any;
utilities.lazyLoad(exports, ["getEnvironments","getEnvironmentsOutput"], () => require("./getEnvironments"));

export { GetGroupArgs, GetGroupResult, GetGroupOutputArgs } from "./getGroup";
export const getGroup: typeof import("./getGroup").getGroup = null as any;
export const getGroupOutput: typeof import("./getGroup").getGroupOutput = null as any;
utilities.lazyLoad(exports, ["getGroup","getGroupOutput"], () => require("./getGroup"));

export { GetSecretsArgs, GetSecretsResult, GetSecretsOutputArgs } from "./getSecrets";
export const getSecrets: typeof import("./getSecrets").getSecrets = null as any;
export const getSecretsOutput: typeof import("./getSecrets").getSecretsOutput = null as any;
utilities.lazyLoad(exports, ["getSecrets","getSecretsOutput"], () => require("./getSecrets"));

export { GetUserArgs, GetUserResult, GetUserOutputArgs } from "./getUser";
export const getUser: typeof import("./getUser").getUser = null as any;
export const getUserOutput: typeof import("./getUser").getUserOutput = null as any;
utilities.lazyLoad(exports, ["getUser","getUserOutput"], () => require("./getUser"));

export { GroupArgs, GroupState } from "./group";
export type Group = import("./group").Group;
export const Group: typeof import("./group").Group = null as any;
utilities.lazyLoad(exports, ["Group"], () => require("./group"));

export { GroupMemberArgs, GroupMemberState } from "./groupMember";
export type GroupMember = import("./groupMember").GroupMember;
export const GroupMember: typeof import("./groupMember").GroupMember = null as any;
utilities.lazyLoad(exports, ["GroupMember"], () => require("./groupMember"));

export { GroupMembersArgs, GroupMembersState } from "./groupMembers";
export type GroupMembers = import("./groupMembers").GroupMembers;
export const GroupMembers: typeof import("./groupMembers").GroupMembers = null as any;
utilities.lazyLoad(exports, ["GroupMembers"], () => require("./groupMembers"));

export { IntegrationAwsIamUserKeysArgs, IntegrationAwsIamUserKeysState } from "./integrationAwsIamUserKeys";
export type IntegrationAwsIamUserKeys = import("./integrationAwsIamUserKeys").IntegrationAwsIamUserKeys;
export const IntegrationAwsIamUserKeys: typeof import("./integrationAwsIamUserKeys").IntegrationAwsIamUserKeys = null as any;
utilities.lazyLoad(exports, ["IntegrationAwsIamUserKeys"], () => require("./integrationAwsIamUserKeys"));

export { IntegrationAwsMssqlArgs, IntegrationAwsMssqlState } from "./integrationAwsMssql";
export type IntegrationAwsMssql = import("./integrationAwsMssql").IntegrationAwsMssql;
export const IntegrationAwsMssql: typeof import("./integrationAwsMssql").IntegrationAwsMssql = null as any;
utilities.lazyLoad(exports, ["IntegrationAwsMssql"], () => require("./integrationAwsMssql"));

export { IntegrationAwsMysqlArgs, IntegrationAwsMysqlState } from "./integrationAwsMysql";
export type IntegrationAwsMysql = import("./integrationAwsMysql").IntegrationAwsMysql;
export const IntegrationAwsMysql: typeof import("./integrationAwsMysql").IntegrationAwsMysql = null as any;
utilities.lazyLoad(exports, ["IntegrationAwsMysql"], () => require("./integrationAwsMysql"));

export { IntegrationAwsParameterStoreArgs, IntegrationAwsParameterStoreState } from "./integrationAwsParameterStore";
export type IntegrationAwsParameterStore = import("./integrationAwsParameterStore").IntegrationAwsParameterStore;
export const IntegrationAwsParameterStore: typeof import("./integrationAwsParameterStore").IntegrationAwsParameterStore = null as any;
utilities.lazyLoad(exports, ["IntegrationAwsParameterStore"], () => require("./integrationAwsParameterStore"));

export { IntegrationAwsPostgresArgs, IntegrationAwsPostgresState } from "./integrationAwsPostgres";
export type IntegrationAwsPostgres = import("./integrationAwsPostgres").IntegrationAwsPostgres;
export const IntegrationAwsPostgres: typeof import("./integrationAwsPostgres").IntegrationAwsPostgres = null as any;
utilities.lazyLoad(exports, ["IntegrationAwsPostgres"], () => require("./integrationAwsPostgres"));

export { IntegrationAwsSecretsManagerArgs, IntegrationAwsSecretsManagerState } from "./integrationAwsSecretsManager";
export type IntegrationAwsSecretsManager = import("./integrationAwsSecretsManager").IntegrationAwsSecretsManager;
export const IntegrationAwsSecretsManager: typeof import("./integrationAwsSecretsManager").IntegrationAwsSecretsManager = null as any;
utilities.lazyLoad(exports, ["IntegrationAwsSecretsManager"], () => require("./integrationAwsSecretsManager"));

export { IntegrationAzureVaultServicePrincipalArgs, IntegrationAzureVaultServicePrincipalState } from "./integrationAzureVaultServicePrincipal";
export type IntegrationAzureVaultServicePrincipal = import("./integrationAzureVaultServicePrincipal").IntegrationAzureVaultServicePrincipal;
export const IntegrationAzureVaultServicePrincipal: typeof import("./integrationAzureVaultServicePrincipal").IntegrationAzureVaultServicePrincipal = null as any;
utilities.lazyLoad(exports, ["IntegrationAzureVaultServicePrincipal"], () => require("./integrationAzureVaultServicePrincipal"));

export { IntegrationCircleciArgs, IntegrationCircleciState } from "./integrationCircleci";
export type IntegrationCircleci = import("./integrationCircleci").IntegrationCircleci;
export const IntegrationCircleci: typeof import("./integrationCircleci").IntegrationCircleci = null as any;
utilities.lazyLoad(exports, ["IntegrationCircleci"], () => require("./integrationCircleci"));

export { IntegrationCloudflareTokensArgs, IntegrationCloudflareTokensState } from "./integrationCloudflareTokens";
export type IntegrationCloudflareTokens = import("./integrationCloudflareTokens").IntegrationCloudflareTokens;
export const IntegrationCloudflareTokens: typeof import("./integrationCloudflareTokens").IntegrationCloudflareTokens = null as any;
utilities.lazyLoad(exports, ["IntegrationCloudflareTokens"], () => require("./integrationCloudflareTokens"));

export { IntegrationExternalIdArgs, IntegrationExternalIdState } from "./integrationExternalId";
export type IntegrationExternalId = import("./integrationExternalId").IntegrationExternalId;
export const IntegrationExternalId: typeof import("./integrationExternalId").IntegrationExternalId = null as any;
utilities.lazyLoad(exports, ["IntegrationExternalId"], () => require("./integrationExternalId"));

export { IntegrationFlyioArgs, IntegrationFlyioState } from "./integrationFlyio";
export type IntegrationFlyio = import("./integrationFlyio").IntegrationFlyio;
export const IntegrationFlyio: typeof import("./integrationFlyio").IntegrationFlyio = null as any;
utilities.lazyLoad(exports, ["IntegrationFlyio"], () => require("./integrationFlyio"));

export { IntegrationGcpCloudsqlMysqlArgs, IntegrationGcpCloudsqlMysqlState } from "./integrationGcpCloudsqlMysql";
export type IntegrationGcpCloudsqlMysql = import("./integrationGcpCloudsqlMysql").IntegrationGcpCloudsqlMysql;
export const IntegrationGcpCloudsqlMysql: typeof import("./integrationGcpCloudsqlMysql").IntegrationGcpCloudsqlMysql = null as any;
utilities.lazyLoad(exports, ["IntegrationGcpCloudsqlMysql"], () => require("./integrationGcpCloudsqlMysql"));

export { IntegrationGcpCloudsqlPostgresArgs, IntegrationGcpCloudsqlPostgresState } from "./integrationGcpCloudsqlPostgres";
export type IntegrationGcpCloudsqlPostgres = import("./integrationGcpCloudsqlPostgres").IntegrationGcpCloudsqlPostgres;
export const IntegrationGcpCloudsqlPostgres: typeof import("./integrationGcpCloudsqlPostgres").IntegrationGcpCloudsqlPostgres = null as any;
utilities.lazyLoad(exports, ["IntegrationGcpCloudsqlPostgres"], () => require("./integrationGcpCloudsqlPostgres"));

export { IntegrationGcpCloudsqlSqlserverArgs, IntegrationGcpCloudsqlSqlserverState } from "./integrationGcpCloudsqlSqlserver";
export type IntegrationGcpCloudsqlSqlserver = import("./integrationGcpCloudsqlSqlserver").IntegrationGcpCloudsqlSqlserver;
export const IntegrationGcpCloudsqlSqlserver: typeof import("./integrationGcpCloudsqlSqlserver").IntegrationGcpCloudsqlSqlserver = null as any;
utilities.lazyLoad(exports, ["IntegrationGcpCloudsqlSqlserver"], () => require("./integrationGcpCloudsqlSqlserver"));

export { IntegrationGcpSecretManagerArgs, IntegrationGcpSecretManagerState } from "./integrationGcpSecretManager";
export type IntegrationGcpSecretManager = import("./integrationGcpSecretManager").IntegrationGcpSecretManager;
export const IntegrationGcpSecretManager: typeof import("./integrationGcpSecretManager").IntegrationGcpSecretManager = null as any;
utilities.lazyLoad(exports, ["IntegrationGcpSecretManager"], () => require("./integrationGcpSecretManager"));

export { IntegrationGcpServiceAccountKeysArgs, IntegrationGcpServiceAccountKeysState } from "./integrationGcpServiceAccountKeys";
export type IntegrationGcpServiceAccountKeys = import("./integrationGcpServiceAccountKeys").IntegrationGcpServiceAccountKeys;
export const IntegrationGcpServiceAccountKeys: typeof import("./integrationGcpServiceAccountKeys").IntegrationGcpServiceAccountKeys = null as any;
utilities.lazyLoad(exports, ["IntegrationGcpServiceAccountKeys"], () => require("./integrationGcpServiceAccountKeys"));

export { IntegrationMongodbAtlasArgs, IntegrationMongodbAtlasState } from "./integrationMongodbAtlas";
export type IntegrationMongodbAtlas = import("./integrationMongodbAtlas").IntegrationMongodbAtlas;
export const IntegrationMongodbAtlas: typeof import("./integrationMongodbAtlas").IntegrationMongodbAtlas = null as any;
utilities.lazyLoad(exports, ["IntegrationMongodbAtlas"], () => require("./integrationMongodbAtlas"));

export { IntegrationSendgridArgs, IntegrationSendgridState } from "./integrationSendgrid";
export type IntegrationSendgrid = import("./integrationSendgrid").IntegrationSendgrid;
export const IntegrationSendgrid: typeof import("./integrationSendgrid").IntegrationSendgrid = null as any;
utilities.lazyLoad(exports, ["IntegrationSendgrid"], () => require("./integrationSendgrid"));

export { IntegrationTerraformCloudArgs, IntegrationTerraformCloudState } from "./integrationTerraformCloud";
export type IntegrationTerraformCloud = import("./integrationTerraformCloud").IntegrationTerraformCloud;
export const IntegrationTerraformCloud: typeof import("./integrationTerraformCloud").IntegrationTerraformCloud = null as any;
utilities.lazyLoad(exports, ["IntegrationTerraformCloud"], () => require("./integrationTerraformCloud"));

export { IntegrationTwilioArgs, IntegrationTwilioState } from "./integrationTwilio";
export type IntegrationTwilio = import("./integrationTwilio").IntegrationTwilio;
export const IntegrationTwilio: typeof import("./integrationTwilio").IntegrationTwilio = null as any;
utilities.lazyLoad(exports, ["IntegrationTwilio"], () => require("./integrationTwilio"));

export { ProjectArgs, ProjectState } from "./project";
export type Project = import("./project").Project;
export const Project: typeof import("./project").Project = null as any;
utilities.lazyLoad(exports, ["Project"], () => require("./project"));

export { ProjectMemberGroupArgs, ProjectMemberGroupState } from "./projectMemberGroup";
export type ProjectMemberGroup = import("./projectMemberGroup").ProjectMemberGroup;
export const ProjectMemberGroup: typeof import("./projectMemberGroup").ProjectMemberGroup = null as any;
utilities.lazyLoad(exports, ["ProjectMemberGroup"], () => require("./projectMemberGroup"));

export { ProjectMemberServiceAccountArgs, ProjectMemberServiceAccountState } from "./projectMemberServiceAccount";
export type ProjectMemberServiceAccount = import("./projectMemberServiceAccount").ProjectMemberServiceAccount;
export const ProjectMemberServiceAccount: typeof import("./projectMemberServiceAccount").ProjectMemberServiceAccount = null as any;
utilities.lazyLoad(exports, ["ProjectMemberServiceAccount"], () => require("./projectMemberServiceAccount"));

export { ProjectMemberUserArgs, ProjectMemberUserState } from "./projectMemberUser";
export type ProjectMemberUser = import("./projectMemberUser").ProjectMemberUser;
export const ProjectMemberUser: typeof import("./projectMemberUser").ProjectMemberUser = null as any;
utilities.lazyLoad(exports, ["ProjectMemberUser"], () => require("./projectMemberUser"));

export { ProjectRoleArgs, ProjectRoleState } from "./projectRole";
export type ProjectRole = import("./projectRole").ProjectRole;
export const ProjectRole: typeof import("./projectRole").ProjectRole = null as any;
utilities.lazyLoad(exports, ["ProjectRole"], () => require("./projectRole"));

export * from "./provider";
import { Provider } from "./provider";

export { RotatedSecretAwsIamUserKeysArgs, RotatedSecretAwsIamUserKeysState } from "./rotatedSecretAwsIamUserKeys";
export type RotatedSecretAwsIamUserKeys = import("./rotatedSecretAwsIamUserKeys").RotatedSecretAwsIamUserKeys;
export const RotatedSecretAwsIamUserKeys: typeof import("./rotatedSecretAwsIamUserKeys").RotatedSecretAwsIamUserKeys = null as any;
utilities.lazyLoad(exports, ["RotatedSecretAwsIamUserKeys"], () => require("./rotatedSecretAwsIamUserKeys"));

export { RotatedSecretAwsMssqlArgs, RotatedSecretAwsMssqlState } from "./rotatedSecretAwsMssql";
export type RotatedSecretAwsMssql = import("./rotatedSecretAwsMssql").RotatedSecretAwsMssql;
export const RotatedSecretAwsMssql: typeof import("./rotatedSecretAwsMssql").RotatedSecretAwsMssql = null as any;
utilities.lazyLoad(exports, ["RotatedSecretAwsMssql"], () => require("./rotatedSecretAwsMssql"));

export { RotatedSecretAwsMysqlArgs, RotatedSecretAwsMysqlState } from "./rotatedSecretAwsMysql";
export type RotatedSecretAwsMysql = import("./rotatedSecretAwsMysql").RotatedSecretAwsMysql;
export const RotatedSecretAwsMysql: typeof import("./rotatedSecretAwsMysql").RotatedSecretAwsMysql = null as any;
utilities.lazyLoad(exports, ["RotatedSecretAwsMysql"], () => require("./rotatedSecretAwsMysql"));

export { RotatedSecretAwsPostgresArgs, RotatedSecretAwsPostgresState } from "./rotatedSecretAwsPostgres";
export type RotatedSecretAwsPostgres = import("./rotatedSecretAwsPostgres").RotatedSecretAwsPostgres;
export const RotatedSecretAwsPostgres: typeof import("./rotatedSecretAwsPostgres").RotatedSecretAwsPostgres = null as any;
utilities.lazyLoad(exports, ["RotatedSecretAwsPostgres"], () => require("./rotatedSecretAwsPostgres"));

export { RotatedSecretCloudflareTokensArgs, RotatedSecretCloudflareTokensState } from "./rotatedSecretCloudflareTokens";
export type RotatedSecretCloudflareTokens = import("./rotatedSecretCloudflareTokens").RotatedSecretCloudflareTokens;
export const RotatedSecretCloudflareTokens: typeof import("./rotatedSecretCloudflareTokens").RotatedSecretCloudflareTokens = null as any;
utilities.lazyLoad(exports, ["RotatedSecretCloudflareTokens"], () => require("./rotatedSecretCloudflareTokens"));

export { RotatedSecretGcpCloudsqlArgs, RotatedSecretGcpCloudsqlState } from "./rotatedSecretGcpCloudsql";
export type RotatedSecretGcpCloudsql = import("./rotatedSecretGcpCloudsql").RotatedSecretGcpCloudsql;
export const RotatedSecretGcpCloudsql: typeof import("./rotatedSecretGcpCloudsql").RotatedSecretGcpCloudsql = null as any;
utilities.lazyLoad(exports, ["RotatedSecretGcpCloudsql"], () => require("./rotatedSecretGcpCloudsql"));

export { RotatedSecretGcpServiceAccountKeysArgs, RotatedSecretGcpServiceAccountKeysState } from "./rotatedSecretGcpServiceAccountKeys";
export type RotatedSecretGcpServiceAccountKeys = import("./rotatedSecretGcpServiceAccountKeys").RotatedSecretGcpServiceAccountKeys;
export const RotatedSecretGcpServiceAccountKeys: typeof import("./rotatedSecretGcpServiceAccountKeys").RotatedSecretGcpServiceAccountKeys = null as any;
utilities.lazyLoad(exports, ["RotatedSecretGcpServiceAccountKeys"], () => require("./rotatedSecretGcpServiceAccountKeys"));

export { RotatedSecretMongodbAtlasArgs, RotatedSecretMongodbAtlasState } from "./rotatedSecretMongodbAtlas";
export type RotatedSecretMongodbAtlas = import("./rotatedSecretMongodbAtlas").RotatedSecretMongodbAtlas;
export const RotatedSecretMongodbAtlas: typeof import("./rotatedSecretMongodbAtlas").RotatedSecretMongodbAtlas = null as any;
utilities.lazyLoad(exports, ["RotatedSecretMongodbAtlas"], () => require("./rotatedSecretMongodbAtlas"));

export { RotatedSecretSendgridArgs, RotatedSecretSendgridState } from "./rotatedSecretSendgrid";
export type RotatedSecretSendgrid = import("./rotatedSecretSendgrid").RotatedSecretSendgrid;
export const RotatedSecretSendgrid: typeof import("./rotatedSecretSendgrid").RotatedSecretSendgrid = null as any;
utilities.lazyLoad(exports, ["RotatedSecretSendgrid"], () => require("./rotatedSecretSendgrid"));

export { RotatedSecretTwilioArgs, RotatedSecretTwilioState } from "./rotatedSecretTwilio";
export type RotatedSecretTwilio = import("./rotatedSecretTwilio").RotatedSecretTwilio;
export const RotatedSecretTwilio: typeof import("./rotatedSecretTwilio").RotatedSecretTwilio = null as any;
utilities.lazyLoad(exports, ["RotatedSecretTwilio"], () => require("./rotatedSecretTwilio"));

export { SecretArgs, SecretState } from "./secret";
export type Secret = import("./secret").Secret;
export const Secret: typeof import("./secret").Secret = null as any;
utilities.lazyLoad(exports, ["Secret"], () => require("./secret"));

export { SecretsSyncAwsParameterStoreArgs, SecretsSyncAwsParameterStoreState } from "./secretsSyncAwsParameterStore";
export type SecretsSyncAwsParameterStore = import("./secretsSyncAwsParameterStore").SecretsSyncAwsParameterStore;
export const SecretsSyncAwsParameterStore: typeof import("./secretsSyncAwsParameterStore").SecretsSyncAwsParameterStore = null as any;
utilities.lazyLoad(exports, ["SecretsSyncAwsParameterStore"], () => require("./secretsSyncAwsParameterStore"));

export { SecretsSyncAwsSecretsManagerArgs, SecretsSyncAwsSecretsManagerState } from "./secretsSyncAwsSecretsManager";
export type SecretsSyncAwsSecretsManager = import("./secretsSyncAwsSecretsManager").SecretsSyncAwsSecretsManager;
export const SecretsSyncAwsSecretsManager: typeof import("./secretsSyncAwsSecretsManager").SecretsSyncAwsSecretsManager = null as any;
utilities.lazyLoad(exports, ["SecretsSyncAwsSecretsManager"], () => require("./secretsSyncAwsSecretsManager"));

export { SecretsSyncAzureVaultArgs, SecretsSyncAzureVaultState } from "./secretsSyncAzureVault";
export type SecretsSyncAzureVault = import("./secretsSyncAzureVault").SecretsSyncAzureVault;
export const SecretsSyncAzureVault: typeof import("./secretsSyncAzureVault").SecretsSyncAzureVault = null as any;
utilities.lazyLoad(exports, ["SecretsSyncAzureVault"], () => require("./secretsSyncAzureVault"));

export { SecretsSyncCircleciArgs, SecretsSyncCircleciState } from "./secretsSyncCircleci";
export type SecretsSyncCircleci = import("./secretsSyncCircleci").SecretsSyncCircleci;
export const SecretsSyncCircleci: typeof import("./secretsSyncCircleci").SecretsSyncCircleci = null as any;
utilities.lazyLoad(exports, ["SecretsSyncCircleci"], () => require("./secretsSyncCircleci"));

export { SecretsSyncFlyioArgs, SecretsSyncFlyioState } from "./secretsSyncFlyio";
export type SecretsSyncFlyio = import("./secretsSyncFlyio").SecretsSyncFlyio;
export const SecretsSyncFlyio: typeof import("./secretsSyncFlyio").SecretsSyncFlyio = null as any;
utilities.lazyLoad(exports, ["SecretsSyncFlyio"], () => require("./secretsSyncFlyio"));

export { SecretsSyncGcpSecretManagerArgs, SecretsSyncGcpSecretManagerState } from "./secretsSyncGcpSecretManager";
export type SecretsSyncGcpSecretManager = import("./secretsSyncGcpSecretManager").SecretsSyncGcpSecretManager;
export const SecretsSyncGcpSecretManager: typeof import("./secretsSyncGcpSecretManager").SecretsSyncGcpSecretManager = null as any;
utilities.lazyLoad(exports, ["SecretsSyncGcpSecretManager"], () => require("./secretsSyncGcpSecretManager"));

export { SecretsSyncGithubActionsArgs, SecretsSyncGithubActionsState } from "./secretsSyncGithubActions";
export type SecretsSyncGithubActions = import("./secretsSyncGithubActions").SecretsSyncGithubActions;
export const SecretsSyncGithubActions: typeof import("./secretsSyncGithubActions").SecretsSyncGithubActions = null as any;
utilities.lazyLoad(exports, ["SecretsSyncGithubActions"], () => require("./secretsSyncGithubActions"));

export { SecretsSyncGithubCodespacesArgs, SecretsSyncGithubCodespacesState } from "./secretsSyncGithubCodespaces";
export type SecretsSyncGithubCodespaces = import("./secretsSyncGithubCodespaces").SecretsSyncGithubCodespaces;
export const SecretsSyncGithubCodespaces: typeof import("./secretsSyncGithubCodespaces").SecretsSyncGithubCodespaces = null as any;
utilities.lazyLoad(exports, ["SecretsSyncGithubCodespaces"], () => require("./secretsSyncGithubCodespaces"));

export { SecretsSyncGithubDependabotArgs, SecretsSyncGithubDependabotState } from "./secretsSyncGithubDependabot";
export type SecretsSyncGithubDependabot = import("./secretsSyncGithubDependabot").SecretsSyncGithubDependabot;
export const SecretsSyncGithubDependabot: typeof import("./secretsSyncGithubDependabot").SecretsSyncGithubDependabot = null as any;
utilities.lazyLoad(exports, ["SecretsSyncGithubDependabot"], () => require("./secretsSyncGithubDependabot"));

export { SecretsSyncTerraformCloudArgs, SecretsSyncTerraformCloudState } from "./secretsSyncTerraformCloud";
export type SecretsSyncTerraformCloud = import("./secretsSyncTerraformCloud").SecretsSyncTerraformCloud;
export const SecretsSyncTerraformCloud: typeof import("./secretsSyncTerraformCloud").SecretsSyncTerraformCloud = null as any;
utilities.lazyLoad(exports, ["SecretsSyncTerraformCloud"], () => require("./secretsSyncTerraformCloud"));

export { ServiceAccountArgs, ServiceAccountState } from "./serviceAccount";
export type ServiceAccount = import("./serviceAccount").ServiceAccount;
export const ServiceAccount: typeof import("./serviceAccount").ServiceAccount = null as any;
utilities.lazyLoad(exports, ["ServiceAccount"], () => require("./serviceAccount"));

export { ServiceAccountIdentityArgs, ServiceAccountIdentityState } from "./serviceAccountIdentity";
export type ServiceAccountIdentity = import("./serviceAccountIdentity").ServiceAccountIdentity;
export const ServiceAccountIdentity: typeof import("./serviceAccountIdentity").ServiceAccountIdentity = null as any;
utilities.lazyLoad(exports, ["ServiceAccountIdentity"], () => require("./serviceAccountIdentity"));

export { ServiceAccountTokenArgs, ServiceAccountTokenState } from "./serviceAccountToken";
export type ServiceAccountToken = import("./serviceAccountToken").ServiceAccountToken;
export const ServiceAccountToken: typeof import("./serviceAccountToken").ServiceAccountToken = null as any;
utilities.lazyLoad(exports, ["ServiceAccountToken"], () => require("./serviceAccountToken"));

export { ServiceTokenArgs, ServiceTokenState } from "./serviceToken";
export type ServiceToken = import("./serviceToken").ServiceToken;
export const ServiceToken: typeof import("./serviceToken").ServiceToken = null as any;
utilities.lazyLoad(exports, ["ServiceToken"], () => require("./serviceToken"));

export { TrustedIpsArgs, TrustedIpsState } from "./trustedIps";
export type TrustedIps = import("./trustedIps").TrustedIps;
export const TrustedIps: typeof import("./trustedIps").TrustedIps = null as any;
utilities.lazyLoad(exports, ["TrustedIps"], () => require("./trustedIps"));

export { WebhookArgs, WebhookState } from "./webhook";
export type Webhook = import("./webhook").Webhook;
export const Webhook: typeof import("./webhook").Webhook = null as any;
utilities.lazyLoad(exports, ["Webhook"], () => require("./webhook"));

export { WorkplaceRoleArgs, WorkplaceRoleState } from "./workplaceRole";
export type WorkplaceRole = import("./workplaceRole").WorkplaceRole;
export const WorkplaceRole: typeof import("./workplaceRole").WorkplaceRole = null as any;
utilities.lazyLoad(exports, ["WorkplaceRole"], () => require("./workplaceRole"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "doppler:index/changeRequestPolicy:ChangeRequestPolicy":
                return new ChangeRequestPolicy(name, <any>undefined, { urn })
            case "doppler:index/config:Config":
                return new Config(name, <any>undefined, { urn })
            case "doppler:index/environment:Environment":
                return new Environment(name, <any>undefined, { urn })
            case "doppler:index/group:Group":
                return new Group(name, <any>undefined, { urn })
            case "doppler:index/groupMember:GroupMember":
                return new GroupMember(name, <any>undefined, { urn })
            case "doppler:index/groupMembers:GroupMembers":
                return new GroupMembers(name, <any>undefined, { urn })
            case "doppler:index/integrationAwsIamUserKeys:IntegrationAwsIamUserKeys":
                return new IntegrationAwsIamUserKeys(name, <any>undefined, { urn })
            case "doppler:index/integrationAwsMssql:IntegrationAwsMssql":
                return new IntegrationAwsMssql(name, <any>undefined, { urn })
            case "doppler:index/integrationAwsMysql:IntegrationAwsMysql":
                return new IntegrationAwsMysql(name, <any>undefined, { urn })
            case "doppler:index/integrationAwsParameterStore:IntegrationAwsParameterStore":
                return new IntegrationAwsParameterStore(name, <any>undefined, { urn })
            case "doppler:index/integrationAwsPostgres:IntegrationAwsPostgres":
                return new IntegrationAwsPostgres(name, <any>undefined, { urn })
            case "doppler:index/integrationAwsSecretsManager:IntegrationAwsSecretsManager":
                return new IntegrationAwsSecretsManager(name, <any>undefined, { urn })
            case "doppler:index/integrationAzureVaultServicePrincipal:IntegrationAzureVaultServicePrincipal":
                return new IntegrationAzureVaultServicePrincipal(name, <any>undefined, { urn })
            case "doppler:index/integrationCircleci:IntegrationCircleci":
                return new IntegrationCircleci(name, <any>undefined, { urn })
            case "doppler:index/integrationCloudflareTokens:IntegrationCloudflareTokens":
                return new IntegrationCloudflareTokens(name, <any>undefined, { urn })
            case "doppler:index/integrationExternalId:IntegrationExternalId":
                return new IntegrationExternalId(name, <any>undefined, { urn })
            case "doppler:index/integrationFlyio:IntegrationFlyio":
                return new IntegrationFlyio(name, <any>undefined, { urn })
            case "doppler:index/integrationGcpCloudsqlMysql:IntegrationGcpCloudsqlMysql":
                return new IntegrationGcpCloudsqlMysql(name, <any>undefined, { urn })
            case "doppler:index/integrationGcpCloudsqlPostgres:IntegrationGcpCloudsqlPostgres":
                return new IntegrationGcpCloudsqlPostgres(name, <any>undefined, { urn })
            case "doppler:index/integrationGcpCloudsqlSqlserver:IntegrationGcpCloudsqlSqlserver":
                return new IntegrationGcpCloudsqlSqlserver(name, <any>undefined, { urn })
            case "doppler:index/integrationGcpSecretManager:IntegrationGcpSecretManager":
                return new IntegrationGcpSecretManager(name, <any>undefined, { urn })
            case "doppler:index/integrationGcpServiceAccountKeys:IntegrationGcpServiceAccountKeys":
                return new IntegrationGcpServiceAccountKeys(name, <any>undefined, { urn })
            case "doppler:index/integrationMongodbAtlas:IntegrationMongodbAtlas":
                return new IntegrationMongodbAtlas(name, <any>undefined, { urn })
            case "doppler:index/integrationSendgrid:IntegrationSendgrid":
                return new IntegrationSendgrid(name, <any>undefined, { urn })
            case "doppler:index/integrationTerraformCloud:IntegrationTerraformCloud":
                return new IntegrationTerraformCloud(name, <any>undefined, { urn })
            case "doppler:index/integrationTwilio:IntegrationTwilio":
                return new IntegrationTwilio(name, <any>undefined, { urn })
            case "doppler:index/project:Project":
                return new Project(name, <any>undefined, { urn })
            case "doppler:index/projectMemberGroup:ProjectMemberGroup":
                return new ProjectMemberGroup(name, <any>undefined, { urn })
            case "doppler:index/projectMemberServiceAccount:ProjectMemberServiceAccount":
                return new ProjectMemberServiceAccount(name, <any>undefined, { urn })
            case "doppler:index/projectMemberUser:ProjectMemberUser":
                return new ProjectMemberUser(name, <any>undefined, { urn })
            case "doppler:index/projectRole:ProjectRole":
                return new ProjectRole(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretAwsIamUserKeys:RotatedSecretAwsIamUserKeys":
                return new RotatedSecretAwsIamUserKeys(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretAwsMssql:RotatedSecretAwsMssql":
                return new RotatedSecretAwsMssql(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretAwsMysql:RotatedSecretAwsMysql":
                return new RotatedSecretAwsMysql(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretAwsPostgres:RotatedSecretAwsPostgres":
                return new RotatedSecretAwsPostgres(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretCloudflareTokens:RotatedSecretCloudflareTokens":
                return new RotatedSecretCloudflareTokens(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretGcpCloudsql:RotatedSecretGcpCloudsql":
                return new RotatedSecretGcpCloudsql(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretGcpServiceAccountKeys:RotatedSecretGcpServiceAccountKeys":
                return new RotatedSecretGcpServiceAccountKeys(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretMongodbAtlas:RotatedSecretMongodbAtlas":
                return new RotatedSecretMongodbAtlas(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretSendgrid:RotatedSecretSendgrid":
                return new RotatedSecretSendgrid(name, <any>undefined, { urn })
            case "doppler:index/rotatedSecretTwilio:RotatedSecretTwilio":
                return new RotatedSecretTwilio(name, <any>undefined, { urn })
            case "doppler:index/secret:Secret":
                return new Secret(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncAwsParameterStore:SecretsSyncAwsParameterStore":
                return new SecretsSyncAwsParameterStore(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncAwsSecretsManager:SecretsSyncAwsSecretsManager":
                return new SecretsSyncAwsSecretsManager(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncAzureVault:SecretsSyncAzureVault":
                return new SecretsSyncAzureVault(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncCircleci:SecretsSyncCircleci":
                return new SecretsSyncCircleci(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncFlyio:SecretsSyncFlyio":
                return new SecretsSyncFlyio(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncGcpSecretManager:SecretsSyncGcpSecretManager":
                return new SecretsSyncGcpSecretManager(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncGithubActions:SecretsSyncGithubActions":
                return new SecretsSyncGithubActions(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncGithubCodespaces:SecretsSyncGithubCodespaces":
                return new SecretsSyncGithubCodespaces(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncGithubDependabot:SecretsSyncGithubDependabot":
                return new SecretsSyncGithubDependabot(name, <any>undefined, { urn })
            case "doppler:index/secretsSyncTerraformCloud:SecretsSyncTerraformCloud":
                return new SecretsSyncTerraformCloud(name, <any>undefined, { urn })
            case "doppler:index/serviceAccount:ServiceAccount":
                return new ServiceAccount(name, <any>undefined, { urn })
            case "doppler:index/serviceAccountIdentity:ServiceAccountIdentity":
                return new ServiceAccountIdentity(name, <any>undefined, { urn })
            case "doppler:index/serviceAccountToken:ServiceAccountToken":
                return new ServiceAccountToken(name, <any>undefined, { urn })
            case "doppler:index/serviceToken:ServiceToken":
                return new ServiceToken(name, <any>undefined, { urn })
            case "doppler:index/trustedIps:TrustedIps":
                return new TrustedIps(name, <any>undefined, { urn })
            case "doppler:index/webhook:Webhook":
                return new Webhook(name, <any>undefined, { urn })
            case "doppler:index/workplaceRole:WorkplaceRole":
                return new WorkplaceRole(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("doppler", "index/changeRequestPolicy", _module)
pulumi.runtime.registerResourceModule("doppler", "index/config", _module)
pulumi.runtime.registerResourceModule("doppler", "index/environment", _module)
pulumi.runtime.registerResourceModule("doppler", "index/group", _module)
pulumi.runtime.registerResourceModule("doppler", "index/groupMember", _module)
pulumi.runtime.registerResourceModule("doppler", "index/groupMembers", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationAwsIamUserKeys", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationAwsMssql", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationAwsMysql", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationAwsParameterStore", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationAwsPostgres", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationAwsSecretsManager", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationAzureVaultServicePrincipal", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationCircleci", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationCloudflareTokens", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationExternalId", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationFlyio", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationGcpCloudsqlMysql", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationGcpCloudsqlPostgres", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationGcpCloudsqlSqlserver", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationGcpSecretManager", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationGcpServiceAccountKeys", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationMongodbAtlas", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationSendgrid", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationTerraformCloud", _module)
pulumi.runtime.registerResourceModule("doppler", "index/integrationTwilio", _module)
pulumi.runtime.registerResourceModule("doppler", "index/project", _module)
pulumi.runtime.registerResourceModule("doppler", "index/projectMemberGroup", _module)
pulumi.runtime.registerResourceModule("doppler", "index/projectMemberServiceAccount", _module)
pulumi.runtime.registerResourceModule("doppler", "index/projectMemberUser", _module)
pulumi.runtime.registerResourceModule("doppler", "index/projectRole", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretAwsIamUserKeys", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretAwsMssql", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretAwsMysql", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretAwsPostgres", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretCloudflareTokens", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretGcpCloudsql", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretGcpServiceAccountKeys", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretMongodbAtlas", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretSendgrid", _module)
pulumi.runtime.registerResourceModule("doppler", "index/rotatedSecretTwilio", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secret", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncAwsParameterStore", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncAwsSecretsManager", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncAzureVault", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncCircleci", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncFlyio", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncGcpSecretManager", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncGithubActions", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncGithubCodespaces", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncGithubDependabot", _module)
pulumi.runtime.registerResourceModule("doppler", "index/secretsSyncTerraformCloud", _module)
pulumi.runtime.registerResourceModule("doppler", "index/serviceAccount", _module)
pulumi.runtime.registerResourceModule("doppler", "index/serviceAccountIdentity", _module)
pulumi.runtime.registerResourceModule("doppler", "index/serviceAccountToken", _module)
pulumi.runtime.registerResourceModule("doppler", "index/serviceToken", _module)
pulumi.runtime.registerResourceModule("doppler", "index/trustedIps", _module)
pulumi.runtime.registerResourceModule("doppler", "index/webhook", _module)
pulumi.runtime.registerResourceModule("doppler", "index/workplaceRole", _module)
pulumi.runtime.registerResourcePackage("doppler", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:doppler") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
