// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an AWS Parameter Store Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const dopplerParameterStore = new aws.iam.Role("doppler_parameter_store", {
 *     name: "doppler_parameter_store",
 *     assumeRolePolicy: JSON.stringify({
 *         Version: "2012-10-17",
 *         Statement: [{
 *             Effect: "Allow",
 *             Action: "sts:AssumeRole",
 *             Principal: {
 *                 AWS: "arn:aws:iam::299900769157:user/doppler-integration-operator",
 *             },
 *             Condition: {
 *                 StringEquals: {
 *                     "sts:ExternalId": "<YOUR_WORKPLACE_SLUG>",
 *                 },
 *             },
 *         }],
 *     }),
 *     inlinePolicies: [{
 *         name: "doppler_secret_manager",
 *         policy: JSON.stringify({
 *             Version: "2012-10-17",
 *             Statement: [{
 *                 Action: [
 *                     "ssm:PutParameter",
 *                     "ssm:LabelParameterVersion",
 *                     "ssm:DeleteParameter",
 *                     "ssm:RemoveTagsFromResource",
 *                     "ssm:GetParameterHistory",
 *                     "ssm:AddTagsToResource",
 *                     "ssm:GetParametersByPath",
 *                     "ssm:GetParameters",
 *                     "ssm:GetParameter",
 *                     "ssm:DeleteParameters",
 *                 ],
 *                 Effect: "Allow",
 *                 Resource: "*",
 *             }],
 *         }),
 *     }],
 * });
 * const prod = new doppler.IntegrationAwsParameterStore("prod", {
 *     name: "Production",
 *     assumeRoleArn: dopplerParameterStore.arn,
 * });
 * const backendProd = new doppler.SecretsSyncAwsParameterStore("backend_prod", {
 *     integration: prod.id,
 *     project: "backend",
 *     config: "prd",
 *     region: "us-east-1",
 *     path: "/backend/",
 *     secureString: true,
 *     tags: {
 *         myTag: "enabled",
 *     },
 *     deleteBehavior: "leave_in_target",
 * });
 * ```
 */
export class IntegrationAwsParameterStore extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationAwsParameterStore resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationAwsParameterStoreState, opts?: pulumi.CustomResourceOptions): IntegrationAwsParameterStore {
        return new IntegrationAwsParameterStore(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationAwsParameterStore:IntegrationAwsParameterStore';

    /**
     * Returns true if the given object is an instance of IntegrationAwsParameterStore.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationAwsParameterStore {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationAwsParameterStore.__pulumiType;
    }

    /**
     * The ARN of the AWS role for Doppler to assume
     */
    declare public readonly assumeRoleArn: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationAwsParameterStore resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationAwsParameterStoreArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationAwsParameterStoreArgs | IntegrationAwsParameterStoreState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationAwsParameterStoreState | undefined;
            resourceInputs["assumeRoleArn"] = state?.assumeRoleArn;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationAwsParameterStoreArgs | undefined;
            if (args?.assumeRoleArn === undefined && !opts.urn) {
                throw new Error("Missing required property 'assumeRoleArn'");
            }
            resourceInputs["assumeRoleArn"] = args?.assumeRoleArn;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationAwsParameterStore.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationAwsParameterStore resources.
 */
export interface IntegrationAwsParameterStoreState {
    /**
     * The ARN of the AWS role for Doppler to assume
     */
    assumeRoleArn?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationAwsParameterStore resource.
 */
export interface IntegrationAwsParameterStoreArgs {
    /**
     * The ARN of the AWS role for Doppler to assume
     */
    assumeRoleArn: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
