// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an AWS Secrets Manager Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const dopplerSecretsManager = new aws.iam.Role("doppler_secrets_manager", {
 *     name: "doppler_secrets_manager",
 *     assumeRolePolicy: JSON.stringify({
 *         Version: "2012-10-17",
 *         Statement: [{
 *             Effect: "Allow",
 *             Action: "sts:AssumeRole",
 *             Principal: {
 *                 AWS: "arn:aws:iam::299900769157:user/doppler-integration-operator",
 *             },
 *             Condition: {
 *                 StringEquals: {
 *                     "sts:ExternalId": "<YOUR_WORKPLACE_SLUG>",
 *                 },
 *             },
 *         }],
 *     }),
 *     inlinePolicies: [{
 *         name: "doppler_secret_manager",
 *         policy: JSON.stringify({
 *             Version: "2012-10-17",
 *             Statement: [{
 *                 Action: [
 *                     "secretsmanager:GetSecretValue",
 *                     "secretsmanager:DescribeSecret",
 *                     "secretsmanager:PutSecretValue",
 *                     "secretsmanager:CreateSecret",
 *                     "secretsmanager:DeleteSecret",
 *                     "secretsmanager:TagResource",
 *                     "secretsmanager:UpdateSecret",
 *                 ],
 *                 Effect: "Allow",
 *                 Resource: "*",
 *             }],
 *         }),
 *     }],
 * });
 * const prod = new doppler.IntegrationAwsSecretsManager("prod", {
 *     name: "Production",
 *     assumeRoleArn: dopplerSecretsManager.arn,
 * });
 * const backendProd = new doppler.SecretsSyncAwsSecretsManager("backend_prod", {
 *     integration: prod.id,
 *     project: "backend",
 *     config: "prd",
 *     region: "us-east-1",
 *     path: "/backend/",
 *     tags: {
 *         myTag: "enabled",
 *     },
 *     deleteBehavior: "leave_in_target",
 * });
 * ```
 */
export class IntegrationAwsSecretsManager extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationAwsSecretsManager resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationAwsSecretsManagerState, opts?: pulumi.CustomResourceOptions): IntegrationAwsSecretsManager {
        return new IntegrationAwsSecretsManager(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationAwsSecretsManager:IntegrationAwsSecretsManager';

    /**
     * Returns true if the given object is an instance of IntegrationAwsSecretsManager.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationAwsSecretsManager {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationAwsSecretsManager.__pulumiType;
    }

    /**
     * The ARN of the AWS role for Doppler to assume
     */
    declare public readonly assumeRoleArn: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationAwsSecretsManager resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationAwsSecretsManagerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationAwsSecretsManagerArgs | IntegrationAwsSecretsManagerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationAwsSecretsManagerState | undefined;
            resourceInputs["assumeRoleArn"] = state?.assumeRoleArn;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationAwsSecretsManagerArgs | undefined;
            if (args?.assumeRoleArn === undefined && !opts.urn) {
                throw new Error("Missing required property 'assumeRoleArn'");
            }
            resourceInputs["assumeRoleArn"] = args?.assumeRoleArn;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationAwsSecretsManager.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationAwsSecretsManager resources.
 */
export interface IntegrationAwsSecretsManagerState {
    /**
     * The ARN of the AWS role for Doppler to assume
     */
    assumeRoleArn?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationAwsSecretsManager resource.
 */
export interface IntegrationAwsSecretsManagerArgs {
    /**
     * The ARN of the AWS role for Doppler to assume
     */
    assumeRoleArn: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
