// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Twilio Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const iTwilio = new doppler.IntegrationTwilio("i_twilio", {
 *     name: "TF Twilio",
 *     accountSid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 *     keySid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 *     keySecret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 * });
 * const rsTwilio = new doppler.RotatedSecretTwilio("rs_twilio", {
 *     integration: iTwilio.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "TWILIO",
 *     rotationPeriodSec: 2592000,
 * });
 * ```
 */
export class IntegrationTwilio extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationTwilio resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationTwilioState, opts?: pulumi.CustomResourceOptions): IntegrationTwilio {
        return new IntegrationTwilio(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationTwilio:IntegrationTwilio';

    /**
     * Returns true if the given object is an instance of IntegrationTwilio.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationTwilio {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationTwilio.__pulumiType;
    }

    /**
     * The Account SID
     */
    declare public readonly accountSid: pulumi.Output<string>;
    /**
     * The Key Secret
     */
    declare public readonly keySecret: pulumi.Output<string>;
    /**
     * The Key SID (cannot equal accountSID)
     */
    declare public readonly keySid: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationTwilio resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationTwilioArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationTwilioArgs | IntegrationTwilioState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationTwilioState | undefined;
            resourceInputs["accountSid"] = state?.accountSid;
            resourceInputs["keySecret"] = state?.keySecret;
            resourceInputs["keySid"] = state?.keySid;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationTwilioArgs | undefined;
            if (args?.accountSid === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountSid'");
            }
            if (args?.keySecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'keySecret'");
            }
            if (args?.keySid === undefined && !opts.urn) {
                throw new Error("Missing required property 'keySid'");
            }
            resourceInputs["accountSid"] = args?.accountSid;
            resourceInputs["keySecret"] = args?.keySecret ? pulumi.secret(args.keySecret) : undefined;
            resourceInputs["keySid"] = args?.keySid;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["keySecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationTwilio.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationTwilio resources.
 */
export interface IntegrationTwilioState {
    /**
     * The Account SID
     */
    accountSid?: pulumi.Input<string | undefined>;
    /**
     * The Key Secret
     */
    keySecret?: pulumi.Input<string | undefined>;
    /**
     * The Key SID (cannot equal accountSID)
     */
    keySid?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationTwilio resource.
 */
export interface IntegrationTwilioArgs {
    /**
     * The Account SID
     */
    accountSid: pulumi.Input<string>;
    /**
     * The Key Secret
     */
    keySecret: pulumi.Input<string>;
    /**
     * The Key SID (cannot equal accountSID)
     */
    keySid: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
