// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an OpenAI Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const iOpenai = new doppler.IntegrationOpenai("i_openai", {
 *     name: "TF OpenAI",
 *     adminKey: "sk-admin-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 * });
 * const rsOpenai = new doppler.RotatedSecretOpenai("rs_openai", {
 *     integration: iOpenai.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "OPENAI",
 *     rotationPeriodSec: 2592000,
 *     projectId: "proj_xxxxxxxxxxxxxxxxxxxxxxxx",
 * });
 * ```
 */
export class IntegrationOpenai extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationOpenai resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationOpenaiState, opts?: pulumi.CustomResourceOptions): IntegrationOpenai {
        return new IntegrationOpenai(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationOpenai:IntegrationOpenai';

    /**
     * Returns true if the given object is an instance of IntegrationOpenai.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationOpenai {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationOpenai.__pulumiType;
    }

    /**
     * The OpenAI admin key
     */
    declare public readonly adminKey: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationOpenai resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationOpenaiArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationOpenaiArgs | IntegrationOpenaiState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationOpenaiState | undefined;
            resourceInputs["adminKey"] = state?.adminKey;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationOpenaiArgs | undefined;
            if (args?.adminKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'adminKey'");
            }
            resourceInputs["adminKey"] = args?.adminKey ? pulumi.secret(args.adminKey) : undefined;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["adminKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationOpenai.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationOpenai resources.
 */
export interface IntegrationOpenaiState {
    /**
     * The OpenAI admin key
     */
    adminKey?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationOpenai resource.
 */
export interface IntegrationOpenaiArgs {
    /**
     * The OpenAI admin key
     */
    adminKey: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
