// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an Azure Rotated Service Principal Doppler integration using workload identity federation.
 *
 * The managing app registration must already exist in your tenant, with a service principal, admin-consented Microsoft Graph application permissions, and ownership of the target applications it manages.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azuread from "@pulumi/azuread";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const dopplerManager = azuread.getApplication({
 *     clientId: "77ed9112-b7f5-4d1d-a60f-198375e7f265",
 * });
 * const prod = new doppler.IntegrationAzureRotatedServicePrincipalOidc("prod", {
 *     name: "Production",
 *     tenantId: "c77d1b3d-6350-4696-b59f-90dae3e0b41e",
 *     clientId: dopplerManager.then(dopplerManager => dopplerManager.clientId),
 * });
 * const doppler2 = new azuread.ApplicationFederatedIdentityCredential("doppler", {
 *     applicationId: dopplerManager.then(dopplerManager => dopplerManager.id),
 *     displayName: "doppler-production",
 *     issuer: prod.federationIssuer,
 *     subject: prod.federationSubject,
 *     audiences: [prod.federationAudience],
 * });
 * ```
 */
export class IntegrationAzureRotatedServicePrincipalOidc extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationAzureRotatedServicePrincipalOidc resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationAzureRotatedServicePrincipalOidcState, opts?: pulumi.CustomResourceOptions): IntegrationAzureRotatedServicePrincipalOidc {
        return new IntegrationAzureRotatedServicePrincipalOidc(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationAzureRotatedServicePrincipalOidc:IntegrationAzureRotatedServicePrincipalOidc';

    /**
     * Returns true if the given object is an instance of IntegrationAzureRotatedServicePrincipalOidc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationAzureRotatedServicePrincipalOidc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationAzureRotatedServicePrincipalOidc.__pulumiType;
    }

    /**
     * The application (client) ID of the managing service principal
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * The audience to configure on the federated identity credential
     */
    declare public /*out*/ readonly federationAudience: pulumi.Output<string>;
    /**
     * The issuer of the OIDC tokens Doppler issues for this integration
     */
    declare public /*out*/ readonly federationIssuer: pulumi.Output<string>;
    /**
     * The subject of the OIDC tokens Doppler issues for this integration
     */
    declare public /*out*/ readonly federationSubject: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The Azure directory (tenant) ID
     */
    declare public readonly tenantId: pulumi.Output<string>;

    /**
     * Create a IntegrationAzureRotatedServicePrincipalOidc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationAzureRotatedServicePrincipalOidcArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationAzureRotatedServicePrincipalOidcArgs | IntegrationAzureRotatedServicePrincipalOidcState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationAzureRotatedServicePrincipalOidcState | undefined;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["federationAudience"] = state?.federationAudience;
            resourceInputs["federationIssuer"] = state?.federationIssuer;
            resourceInputs["federationSubject"] = state?.federationSubject;
            resourceInputs["name"] = state?.name;
            resourceInputs["tenantId"] = state?.tenantId;
        } else {
            const args = argsOrState as IntegrationAzureRotatedServicePrincipalOidcArgs | undefined;
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.tenantId === undefined && !opts.urn) {
                throw new Error("Missing required property 'tenantId'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["name"] = args?.name;
            resourceInputs["tenantId"] = args?.tenantId;
            resourceInputs["federationAudience"] = undefined /*out*/;
            resourceInputs["federationIssuer"] = undefined /*out*/;
            resourceInputs["federationSubject"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationAzureRotatedServicePrincipalOidc.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationAzureRotatedServicePrincipalOidc resources.
 */
export interface IntegrationAzureRotatedServicePrincipalOidcState {
    /**
     * The application (client) ID of the managing service principal
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * The audience to configure on the federated identity credential
     */
    federationAudience?: pulumi.Input<string | undefined>;
    /**
     * The issuer of the OIDC tokens Doppler issues for this integration
     */
    federationIssuer?: pulumi.Input<string | undefined>;
    /**
     * The subject of the OIDC tokens Doppler issues for this integration
     */
    federationSubject?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The Azure directory (tenant) ID
     */
    tenantId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationAzureRotatedServicePrincipalOidc resource.
 */
export interface IntegrationAzureRotatedServicePrincipalOidcArgs {
    /**
     * The application (client) ID of the managing service principal
     */
    clientId: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The Azure directory (tenant) ID
     */
    tenantId: pulumi.Input<string>;
}
