// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a GCP Secret Manager Doppler integration using workload identity federation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 * import * as gcp from "@pulumi/gcp";
 *
 * const doppler2 = new gcp.iam.WorkloadIdentityPool("doppler", {workloadIdentityPoolId: "doppler-pool"});
 * const dopplerWorkloadIdentityPoolProvider = new gcp.iam.WorkloadIdentityPoolProvider("doppler", {
 *     workloadIdentityPoolId: doppler2.workloadIdentityPoolId,
 *     workloadIdentityPoolProviderId: "doppler",
 *     oidc: {
 *         issuerUri: "https://api.doppler.com",
 *     },
 *     attributeMapping: {
 *         "google.subject": "assertion.sub",
 *     },
 *     attributeCondition: "assertion.workplace == '<YOUR_WORKPLACE_SLUG>'",
 * });
 * const prod = new doppler.IntegrationGcpSecretManagerOidc("prod", {
 *     name: "Production",
 *     gcpWorkloadIdentityProvider: pulumi.interpolate`//iam.googleapis.com/${dopplerWorkloadIdentityPoolProvider.name}`,
 *     gcpProjectId: "your-gcp-project-id",
 *     gcpSecretPrefix: "doppler-",
 * });
 * const dopplerIAMMember = new gcp.projects.IAMMember("doppler", {
 *     project: "your-gcp-project-id",
 *     role: "roles/secretmanager.admin",
 *     member: prod.federationPrincipal,
 *     condition: {
 *         title: "doppler-prefix-only",
 *         expression: "resource.name.startsWith(\"projects/<YOUR_PROJECT_NUMBER>/secrets/doppler-\")",
 *     },
 * });
 * ```
 */
export class IntegrationGcpSecretManagerOidc extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationGcpSecretManagerOidc resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationGcpSecretManagerOidcState, opts?: pulumi.CustomResourceOptions): IntegrationGcpSecretManagerOidc {
        return new IntegrationGcpSecretManagerOidc(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationGcpSecretManagerOidc:IntegrationGcpSecretManagerOidc';

    /**
     * Returns true if the given object is an instance of IntegrationGcpSecretManagerOidc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationGcpSecretManagerOidc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationGcpSecretManagerOidc.__pulumiType;
    }

    /**
     * The IAM principal identifier to grant roles to in GCP for this integration
     */
    declare public /*out*/ readonly federationPrincipal: pulumi.Output<string>;
    /**
     * The ID of the GCP project the integration operates on
     */
    declare public readonly gcpProjectId: pulumi.Output<string>;
    /**
     * The prefix added to any secret created by this integration in GCP. Cannot be changed after the integration is created.
     */
    declare public readonly gcpSecretPrefix: pulumi.Output<string | undefined>;
    /**
     * The full resource name of the workload identity pool provider Doppler federates with, e.g. `//iam.googleapis.com/projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`. Note that it uses the numeric project number, not the project ID.
     */
    declare public readonly gcpWorkloadIdentityProvider: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationGcpSecretManagerOidc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationGcpSecretManagerOidcArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationGcpSecretManagerOidcArgs | IntegrationGcpSecretManagerOidcState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationGcpSecretManagerOidcState | undefined;
            resourceInputs["federationPrincipal"] = state?.federationPrincipal;
            resourceInputs["gcpProjectId"] = state?.gcpProjectId;
            resourceInputs["gcpSecretPrefix"] = state?.gcpSecretPrefix;
            resourceInputs["gcpWorkloadIdentityProvider"] = state?.gcpWorkloadIdentityProvider;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationGcpSecretManagerOidcArgs | undefined;
            if (args?.gcpProjectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'gcpProjectId'");
            }
            if (args?.gcpWorkloadIdentityProvider === undefined && !opts.urn) {
                throw new Error("Missing required property 'gcpWorkloadIdentityProvider'");
            }
            resourceInputs["gcpProjectId"] = args?.gcpProjectId;
            resourceInputs["gcpSecretPrefix"] = args?.gcpSecretPrefix;
            resourceInputs["gcpWorkloadIdentityProvider"] = args?.gcpWorkloadIdentityProvider;
            resourceInputs["name"] = args?.name;
            resourceInputs["federationPrincipal"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationGcpSecretManagerOidc.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationGcpSecretManagerOidc resources.
 */
export interface IntegrationGcpSecretManagerOidcState {
    /**
     * The IAM principal identifier to grant roles to in GCP for this integration
     */
    federationPrincipal?: pulumi.Input<string | undefined>;
    /**
     * The ID of the GCP project the integration operates on
     */
    gcpProjectId?: pulumi.Input<string | undefined>;
    /**
     * The prefix added to any secret created by this integration in GCP. Cannot be changed after the integration is created.
     */
    gcpSecretPrefix?: pulumi.Input<string | undefined>;
    /**
     * The full resource name of the workload identity pool provider Doppler federates with, e.g. `//iam.googleapis.com/projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`. Note that it uses the numeric project number, not the project ID.
     */
    gcpWorkloadIdentityProvider?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationGcpSecretManagerOidc resource.
 */
export interface IntegrationGcpSecretManagerOidcArgs {
    /**
     * The ID of the GCP project the integration operates on
     */
    gcpProjectId: pulumi.Input<string>;
    /**
     * The prefix added to any secret created by this integration in GCP. Cannot be changed after the integration is created.
     */
    gcpSecretPrefix?: pulumi.Input<string | undefined>;
    /**
     * The full resource name of the workload identity pool provider Doppler federates with, e.g. `//iam.googleapis.com/projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`. Note that it uses the numeric project number, not the project ID.
     */
    gcpWorkloadIdentityProvider: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
