// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a AWS IAM User Keys Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const iAwsIamUk = new doppler.IntegrationAwsIamUserKeys("i_aws_iam_uk", {
 *     name: "TF AWS IAM UK",
 *     assumeRoleArn: "arn:aws:iam::xxxxxxxxxxxx:role/xxxxxxxxxxxxxxxx",
 * });
 * const rsAwsIamUk = new doppler.RotatedSecretAwsIamUserKeys("rs_aws_iam_uk", {
 *     integration: iAwsIamUk.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "AWS_IAM_UK",
 *     rotationPeriodSec: 2592000,
 *     username: "xxxxxxxxxxxxx",
 * });
 * ```
 */
export class IntegrationAwsIamUserKeys extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationAwsIamUserKeys resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationAwsIamUserKeysState, opts?: pulumi.CustomResourceOptions): IntegrationAwsIamUserKeys {
        return new IntegrationAwsIamUserKeys(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationAwsIamUserKeys:IntegrationAwsIamUserKeys';

    /**
     * Returns true if the given object is an instance of IntegrationAwsIamUserKeys.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationAwsIamUserKeys {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationAwsIamUserKeys.__pulumiType;
    }

    /**
     * IAM Role ARN for role assumption
     */
    declare public readonly assumeRoleArn: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationAwsIamUserKeys resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationAwsIamUserKeysArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationAwsIamUserKeysArgs | IntegrationAwsIamUserKeysState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationAwsIamUserKeysState | undefined;
            resourceInputs["assumeRoleArn"] = state?.assumeRoleArn;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationAwsIamUserKeysArgs | undefined;
            if (args?.assumeRoleArn === undefined && !opts.urn) {
                throw new Error("Missing required property 'assumeRoleArn'");
            }
            resourceInputs["assumeRoleArn"] = args?.assumeRoleArn;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationAwsIamUserKeys.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationAwsIamUserKeys resources.
 */
export interface IntegrationAwsIamUserKeysState {
    /**
     * IAM Role ARN for role assumption
     */
    assumeRoleArn?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationAwsIamUserKeys resource.
 */
export interface IntegrationAwsIamUserKeysArgs {
    /**
     * IAM Role ARN for role assumption
     */
    assumeRoleArn: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
