// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a MongoDB Atlas Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const config = new pulumi.Config();
 * const dbPassword1 = config.get("dbPassword1") || "";
 * const dbPassword2 = config.get("dbPassword2") || "";
 * const iMongodbAtlas = new doppler.IntegrationMongodbAtlas("i_mongodb_atlas", {
 *     name: "TF MongoDB Atlas",
 *     publicKey: "xxxxxxxx",
 *     privateKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 * });
 * const rsMongodbAtlas = new doppler.RotatedSecretMongodbAtlas("rs_mongodb_atlas", {
 *     integration: iMongodbAtlas.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "MONGODB",
 *     rotationPeriodSec: 2592000,
 *     projectId: "xxxxxxxxxxxxxxxxx",
 *     credentials: [
 *         {
 *             username: "xxxxxxxxx",
 *             password: dbPassword1,
 *         },
 *         {
 *             username: "xxxxxxxxx",
 *             password: dbPassword2,
 *         },
 *     ],
 * }, {
 *     ignoreChanges: ["credentials"],
 * });
 * ```
 */
export class IntegrationMongodbAtlas extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationMongodbAtlas resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationMongodbAtlasState, opts?: pulumi.CustomResourceOptions): IntegrationMongodbAtlas {
        return new IntegrationMongodbAtlas(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationMongodbAtlas:IntegrationMongodbAtlas';

    /**
     * Returns true if the given object is an instance of IntegrationMongodbAtlas.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationMongodbAtlas {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationMongodbAtlas.__pulumiType;
    }

    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The Private Key
     */
    declare public readonly privateKey: pulumi.Output<string>;
    /**
     * The Public Key
     */
    declare public readonly publicKey: pulumi.Output<string>;

    /**
     * Create a IntegrationMongodbAtlas resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationMongodbAtlasArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationMongodbAtlasArgs | IntegrationMongodbAtlasState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationMongodbAtlasState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["privateKey"] = state?.privateKey;
            resourceInputs["publicKey"] = state?.publicKey;
        } else {
            const args = argsOrState as IntegrationMongodbAtlasArgs | undefined;
            if (args?.privateKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'privateKey'");
            }
            if (args?.publicKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'publicKey'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["privateKey"] = args?.privateKey ? pulumi.secret(args.privateKey) : undefined;
            resourceInputs["publicKey"] = args?.publicKey;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["privateKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationMongodbAtlas.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationMongodbAtlas resources.
 */
export interface IntegrationMongodbAtlasState {
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The Private Key
     */
    privateKey?: pulumi.Input<string | undefined>;
    /**
     * The Public Key
     */
    publicKey?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationMongodbAtlas resource.
 */
export interface IntegrationMongodbAtlasArgs {
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The Private Key
     */
    privateKey: pulumi.Input<string>;
    /**
     * The Public Key
     */
    publicKey: pulumi.Input<string>;
}
