// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a CircleCI Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const prod = new doppler.IntegrationCircleci("prod", {
 *     name: "Production",
 *     apiToken: "my_api_token",
 * });
 * const backendProd = new doppler.SecretsSyncCircleci("backend_prod", {
 *     integration: prod.id,
 *     project: "backend",
 *     config: "prd",
 *     resourceType: "project",
 *     resourceId: "github/myorg/myproject",
 *     organizationSlug: "myorg",
 *     deleteBehavior: "leave_in_target",
 * });
 * ```
 */
export class IntegrationCircleci extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationCircleci resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationCircleciState, opts?: pulumi.CustomResourceOptions): IntegrationCircleci {
        return new IntegrationCircleci(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationCircleci:IntegrationCircleci';

    /**
     * Returns true if the given object is an instance of IntegrationCircleci.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationCircleci {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationCircleci.__pulumiType;
    }

    /**
     * A CircleCI API token. See https://docs.doppler.com/docs/circleci for details.
     */
    declare public readonly apiToken: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationCircleci resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationCircleciArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationCircleciArgs | IntegrationCircleciState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationCircleciState | undefined;
            resourceInputs["apiToken"] = state?.apiToken;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationCircleciArgs | undefined;
            if (args?.apiToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'apiToken'");
            }
            resourceInputs["apiToken"] = args?.apiToken ? pulumi.secret(args.apiToken) : undefined;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationCircleci.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationCircleci resources.
 */
export interface IntegrationCircleciState {
    /**
     * A CircleCI API token. See https://docs.doppler.com/docs/circleci for details.
     */
    apiToken?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationCircleci resource.
 */
export interface IntegrationCircleciArgs {
    /**
     * A CircleCI API token. See https://docs.doppler.com/docs/circleci for details.
     */
    apiToken: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
