// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a GCP CloudSQL MySQL Doppler integration using workload identity federation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 * import * as gcp from "@pulumi/gcp";
 *
 * const prod = new doppler.IntegrationGcpCloudsqlMysqlOidc("prod", {
 *     name: "Production",
 *     gcpWorkloadIdentityProvider: "//iam.googleapis.com/projects/123456789/locations/global/workloadIdentityPools/doppler-pool/providers/doppler",
 *     gcpProjectId: "your-gcp-project-id",
 * });
 * const doppler2 = new gcp.projects.IAMMember("doppler", {
 *     project: "your-gcp-project-id",
 *     role: "roles/cloudsql.admin",
 *     member: prod.federationPrincipal,
 * });
 * ```
 */
export class IntegrationGcpCloudsqlMysqlOidc extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationGcpCloudsqlMysqlOidc resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationGcpCloudsqlMysqlOidcState, opts?: pulumi.CustomResourceOptions): IntegrationGcpCloudsqlMysqlOidc {
        return new IntegrationGcpCloudsqlMysqlOidc(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationGcpCloudsqlMysqlOidc:IntegrationGcpCloudsqlMysqlOidc';

    /**
     * Returns true if the given object is an instance of IntegrationGcpCloudsqlMysqlOidc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationGcpCloudsqlMysqlOidc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationGcpCloudsqlMysqlOidc.__pulumiType;
    }

    /**
     * The IAM principal identifier to grant roles to in GCP for this integration
     */
    declare public /*out*/ readonly federationPrincipal: pulumi.Output<string>;
    /**
     * The ID of the GCP project the integration operates on
     */
    declare public readonly gcpProjectId: pulumi.Output<string>;
    /**
     * The full resource name of the workload identity pool provider Doppler federates with, e.g. `//iam.googleapis.com/projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`. Note that it uses the numeric project number, not the project ID.
     */
    declare public readonly gcpWorkloadIdentityProvider: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationGcpCloudsqlMysqlOidc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationGcpCloudsqlMysqlOidcArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationGcpCloudsqlMysqlOidcArgs | IntegrationGcpCloudsqlMysqlOidcState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationGcpCloudsqlMysqlOidcState | undefined;
            resourceInputs["federationPrincipal"] = state?.federationPrincipal;
            resourceInputs["gcpProjectId"] = state?.gcpProjectId;
            resourceInputs["gcpWorkloadIdentityProvider"] = state?.gcpWorkloadIdentityProvider;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationGcpCloudsqlMysqlOidcArgs | undefined;
            if (args?.gcpProjectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'gcpProjectId'");
            }
            if (args?.gcpWorkloadIdentityProvider === undefined && !opts.urn) {
                throw new Error("Missing required property 'gcpWorkloadIdentityProvider'");
            }
            resourceInputs["gcpProjectId"] = args?.gcpProjectId;
            resourceInputs["gcpWorkloadIdentityProvider"] = args?.gcpWorkloadIdentityProvider;
            resourceInputs["name"] = args?.name;
            resourceInputs["federationPrincipal"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationGcpCloudsqlMysqlOidc.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationGcpCloudsqlMysqlOidc resources.
 */
export interface IntegrationGcpCloudsqlMysqlOidcState {
    /**
     * The IAM principal identifier to grant roles to in GCP for this integration
     */
    federationPrincipal?: pulumi.Input<string | undefined>;
    /**
     * The ID of the GCP project the integration operates on
     */
    gcpProjectId?: pulumi.Input<string | undefined>;
    /**
     * The full resource name of the workload identity pool provider Doppler federates with, e.g. `//iam.googleapis.com/projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`. Note that it uses the numeric project number, not the project ID.
     */
    gcpWorkloadIdentityProvider?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationGcpCloudsqlMysqlOidc resource.
 */
export interface IntegrationGcpCloudsqlMysqlOidcArgs {
    /**
     * The ID of the GCP project the integration operates on
     */
    gcpProjectId: pulumi.Input<string>;
    /**
     * The full resource name of the workload identity pool provider Doppler federates with, e.g. `//iam.googleapis.com/projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`. Note that it uses the numeric project number, not the project ID.
     */
    gcpWorkloadIdentityProvider: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
