// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an Azure Rotated Service Principal Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const prod = new doppler.IntegrationAzureRotatedServicePrincipal("prod", {
 *     name: "Production",
 *     tenantId: "c77d1b3d-6350-4696-b59f-90dae3e0b41e",
 *     clientId: "77ed9112-b7f5-4d1d-a60f-198375e7f265",
 *     clientSecret: "kXOQb4juoe~jEqQVQdeXEFhsgIvkmoE0Qz3jBwPo",
 * });
 * ```
 */
export class IntegrationAzureRotatedServicePrincipal extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationAzureRotatedServicePrincipal resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationAzureRotatedServicePrincipalState, opts?: pulumi.CustomResourceOptions): IntegrationAzureRotatedServicePrincipal {
        return new IntegrationAzureRotatedServicePrincipal(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationAzureRotatedServicePrincipal:IntegrationAzureRotatedServicePrincipal';

    /**
     * Returns true if the given object is an instance of IntegrationAzureRotatedServicePrincipal.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationAzureRotatedServicePrincipal {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationAzureRotatedServicePrincipal.__pulumiType;
    }

    /**
     * The application (client) ID of the managing service principal
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * The client secret of the managing service principal
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The Azure directory (tenant) ID
     */
    declare public readonly tenantId: pulumi.Output<string>;

    /**
     * Create a IntegrationAzureRotatedServicePrincipal resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationAzureRotatedServicePrincipalArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationAzureRotatedServicePrincipalArgs | IntegrationAzureRotatedServicePrincipalState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationAzureRotatedServicePrincipalState | undefined;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["clientSecret"] = state?.clientSecret;
            resourceInputs["name"] = state?.name;
            resourceInputs["tenantId"] = state?.tenantId;
        } else {
            const args = argsOrState as IntegrationAzureRotatedServicePrincipalArgs | undefined;
            if (args?.clientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if (args?.clientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if (args?.tenantId === undefined && !opts.urn) {
                throw new Error("Missing required property 'tenantId'");
            }
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["tenantId"] = args?.tenantId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationAzureRotatedServicePrincipal.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationAzureRotatedServicePrincipal resources.
 */
export interface IntegrationAzureRotatedServicePrincipalState {
    /**
     * The application (client) ID of the managing service principal
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * The client secret of the managing service principal
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The Azure directory (tenant) ID
     */
    tenantId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationAzureRotatedServicePrincipal resource.
 */
export interface IntegrationAzureRotatedServicePrincipalArgs {
    /**
     * The application (client) ID of the managing service principal
     */
    clientId: pulumi.Input<string>;
    /**
     * The client secret of the managing service principal
     */
    clientSecret: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The Azure directory (tenant) ID
     */
    tenantId: pulumi.Input<string>;
}
