// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a GCP Secret Manager Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const config = new pulumi.Config();
 * const gcpKey = config.get("gcpKey") || `{
 *   "type": "service_account",
 *   "project_id": "your-gcp-project-id",
 *   "private_key_id": "...",
 *   "private_key": "-----BEGIN PRIVATE KEY-----\\n ... \\n-----END PRIVATE KEY-----\\n",
 *   "client_email": "doppler-secret-manager@your-gcp-project-id.iam.gserviceaccount.com",
 *   "client_id": "12345678901234567890",
 *   "auth_uri": "https://accounts.google.com/o/oauth2/auth",
 *   "token_uri": "https://oauth2.googleapis.com/token",
 *   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
 *   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/doppler-secret-manager%40your-gcp-project-id.iam.gserviceaccount.com",
 *   "universe_domain": "googleapis.com"
 * }
 * `;
 * const prod = new doppler.IntegrationGcpSecretManager("prod", {
 *     name: "prod",
 *     gcpKey: gcpKey,
 *     gcpSecretPrefix: "doppler-",
 * });
 * ```
 */
export class IntegrationGcpSecretManager extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationGcpSecretManager resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationGcpSecretManagerState, opts?: pulumi.CustomResourceOptions): IntegrationGcpSecretManager {
        return new IntegrationGcpSecretManager(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationGcpSecretManager:IntegrationGcpSecretManager';

    /**
     * Returns true if the given object is an instance of IntegrationGcpSecretManager.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationGcpSecretManager {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationGcpSecretManager.__pulumiType;
    }

    /**
     * The IAM Service Account JSON key. See https://docs.doppler.com/docs/gcp-secret-manager for details.
     */
    declare public readonly gcpKey: pulumi.Output<string>;
    /**
     * The prefix added to any secret created by this integration in GCP. See https://docs.doppler.com/docs/gcp-secret-manager for details.
     */
    declare public readonly gcpSecretPrefix: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationGcpSecretManager resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationGcpSecretManagerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationGcpSecretManagerArgs | IntegrationGcpSecretManagerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationGcpSecretManagerState | undefined;
            resourceInputs["gcpKey"] = state?.gcpKey;
            resourceInputs["gcpSecretPrefix"] = state?.gcpSecretPrefix;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationGcpSecretManagerArgs | undefined;
            if (args?.gcpKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'gcpKey'");
            }
            if (args?.gcpSecretPrefix === undefined && !opts.urn) {
                throw new Error("Missing required property 'gcpSecretPrefix'");
            }
            resourceInputs["gcpKey"] = args?.gcpKey ? pulumi.secret(args.gcpKey) : undefined;
            resourceInputs["gcpSecretPrefix"] = args?.gcpSecretPrefix;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["gcpKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationGcpSecretManager.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationGcpSecretManager resources.
 */
export interface IntegrationGcpSecretManagerState {
    /**
     * The IAM Service Account JSON key. See https://docs.doppler.com/docs/gcp-secret-manager for details.
     */
    gcpKey?: pulumi.Input<string | undefined>;
    /**
     * The prefix added to any secret created by this integration in GCP. See https://docs.doppler.com/docs/gcp-secret-manager for details.
     */
    gcpSecretPrefix?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationGcpSecretManager resource.
 */
export interface IntegrationGcpSecretManagerArgs {
    /**
     * The IAM Service Account JSON key. See https://docs.doppler.com/docs/gcp-secret-manager for details.
     */
    gcpKey: pulumi.Input<string>;
    /**
     * The prefix added to any secret created by this integration in GCP. See https://docs.doppler.com/docs/gcp-secret-manager for details.
     */
    gcpSecretPrefix: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
