// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Doppler integration group member.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const awsEngineering = new doppler.IntegrationMemberGroup("aws_engineering", {
 *     integration: prod.slug,
 *     groupSlug: engineering.slug,
 *     role: "consumer",
 * });
 * ```
 */
export class IntegrationMemberGroup extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationMemberGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationMemberGroupState, opts?: pulumi.CustomResourceOptions): IntegrationMemberGroup {
        return new IntegrationMemberGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationMemberGroup:IntegrationMemberGroup';

    /**
     * Returns true if the given object is an instance of IntegrationMemberGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationMemberGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationMemberGroup.__pulumiType;
    }

    /**
     * The slug of the Doppler group
     */
    declare public readonly groupSlug: pulumi.Output<string>;
    /**
     * The slug of the Doppler integration where the access is applied
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * The integration role identifier for the access. Must use either one of the built-in integration role slugs (`admin`, `consumer`, `viewer`, or `noAccess`), or the slug for a custom integration role.
     */
    declare public readonly role: pulumi.Output<string>;

    /**
     * Create a IntegrationMemberGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationMemberGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationMemberGroupArgs | IntegrationMemberGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationMemberGroupState | undefined;
            resourceInputs["groupSlug"] = state?.groupSlug;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["role"] = state?.role;
        } else {
            const args = argsOrState as IntegrationMemberGroupArgs | undefined;
            if (args?.groupSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'groupSlug'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["groupSlug"] = args?.groupSlug;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["role"] = args?.role;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationMemberGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationMemberGroup resources.
 */
export interface IntegrationMemberGroupState {
    /**
     * The slug of the Doppler group
     */
    groupSlug?: pulumi.Input<string | undefined>;
    /**
     * The slug of the Doppler integration where the access is applied
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * The integration role identifier for the access. Must use either one of the built-in integration role slugs (`admin`, `consumer`, `viewer`, or `noAccess`), or the slug for a custom integration role.
     */
    role?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationMemberGroup resource.
 */
export interface IntegrationMemberGroupArgs {
    /**
     * The slug of the Doppler group
     */
    groupSlug: pulumi.Input<string>;
    /**
     * The slug of the Doppler integration where the access is applied
     */
    integration: pulumi.Input<string>;
    /**
     * The integration role identifier for the access. Must use either one of the built-in integration role slugs (`admin`, `consumer`, `viewer`, or `noAccess`), or the slug for a custom integration role.
     */
    role: pulumi.Input<string>;
}
