// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a SendGrid Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const iSendgrid = new doppler.IntegrationSendgrid("i_sendgrid", {
 *     name: "TF SendGrid",
 *     apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 * });
 * const rsSendgrid = new doppler.RotatedSecretSendgrid("rs_sendgrid", {
 *     integration: iSendgrid.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "SENDGRID",
 *     rotationPeriodSec: 2592000,
 *     scopes: [
 *         "alerts.create",
 *         "alerts.read",
 *     ],
 * });
 * ```
 */
export class IntegrationSendgrid extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationSendgrid resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationSendgridState, opts?: pulumi.CustomResourceOptions): IntegrationSendgrid {
        return new IntegrationSendgrid(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationSendgrid:IntegrationSendgrid';

    /**
     * Returns true if the given object is an instance of IntegrationSendgrid.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationSendgrid {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationSendgrid.__pulumiType;
    }

    /**
     * The API Key
     */
    declare public readonly apiKey: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationSendgrid resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationSendgridArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationSendgridArgs | IntegrationSendgridState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationSendgridState | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationSendgridArgs | undefined;
            if (args?.apiKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'apiKey'");
            }
            resourceInputs["apiKey"] = args?.apiKey ? pulumi.secret(args.apiKey) : undefined;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationSendgrid.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationSendgrid resources.
 */
export interface IntegrationSendgridState {
    /**
     * The API Key
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationSendgrid resource.
 */
export interface IntegrationSendgridArgs {
    /**
     * The API Key
     */
    apiKey: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
