// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a GCP CloudSQL MySQL Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const config = new pulumi.Config();
 * const gcpKey = config.get("gcpKey") || `{
 *       "type": "service_account",
 *       "project_id": "xxxxxxxxxxxxxxxxx",
 *       "private_key_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 *       "private_key": "-----BEGIN PRIVATE KEY-----...-----END PRIVATE KEY-----",
 *       "client_email": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 *       "client_id": "xxxxxxxxxxxxxxxxxxxxx"
 * }
 * `;
 * const dbPassword1 = config.get("dbPassword1") || "";
 * const dbPassword2 = config.get("dbPassword2") || "";
 * const iGcpMysql = new doppler.IntegrationGcpCloudsqlMysql("i_gcp_mysql", {
 *     name: "TF GCP MySQL",
 *     gcpKey: gcpKey,
 * });
 * const rsGcpMysql = new doppler.RotatedSecretGcpCloudsql("rs_gcp_mysql", {
 *     integration: iGcpMysql.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "DB",
 *     rotationPeriodSec: 2592000,
 *     databaseInstance: "xxxxxxxxxxxx",
 *     credentials: [
 *         {
 *             username: "xxxxxxxxxxxx",
 *             userHostName: "%",
 *             password: dbPassword1,
 *         },
 *         {
 *             username: "xxxxxxxxxxxx",
 *             userHostName: "%",
 *             password: dbPassword2,
 *         },
 *     ],
 * }, {
 *     ignoreChanges: ["credentials"],
 * });
 * ```
 */
export class IntegrationGcpCloudsqlMysql extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationGcpCloudsqlMysql resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationGcpCloudsqlMysqlState, opts?: pulumi.CustomResourceOptions): IntegrationGcpCloudsqlMysql {
        return new IntegrationGcpCloudsqlMysql(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationGcpCloudsqlMysql:IntegrationGcpCloudsqlMysql';

    /**
     * Returns true if the given object is an instance of IntegrationGcpCloudsqlMysql.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationGcpCloudsqlMysql {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationGcpCloudsqlMysql.__pulumiType;
    }

    /**
     * The GCP service account key
     */
    declare public readonly gcpKey: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationGcpCloudsqlMysql resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationGcpCloudsqlMysqlArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationGcpCloudsqlMysqlArgs | IntegrationGcpCloudsqlMysqlState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationGcpCloudsqlMysqlState | undefined;
            resourceInputs["gcpKey"] = state?.gcpKey;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationGcpCloudsqlMysqlArgs | undefined;
            if (args?.gcpKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'gcpKey'");
            }
            resourceInputs["gcpKey"] = args?.gcpKey ? pulumi.secret(args.gcpKey) : undefined;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["gcpKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationGcpCloudsqlMysql.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationGcpCloudsqlMysql resources.
 */
export interface IntegrationGcpCloudsqlMysqlState {
    /**
     * The GCP service account key
     */
    gcpKey?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationGcpCloudsqlMysql resource.
 */
export interface IntegrationGcpCloudsqlMysqlArgs {
    /**
     * The GCP service account key
     */
    gcpKey: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
