// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Cloudflare Tokens Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const config = new pulumi.Config();
 * const key1 = config.get("key1") || "";
 * const key2 = config.get("key2") || "";
 * const iCf = new doppler.IntegrationCloudflareTokens("i_cf", {
 *     name: "TF Cloudflare",
 *     apiToken: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
 * });
 * const rsCf = new doppler.RotatedSecretCloudflareTokens("rs_cf", {
 *     integration: iCf.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "CLOUDFLARE",
 *     rotationPeriodSec: 2592000,
 *     credentials: [
 *         {
 *             value: key1,
 *         },
 *         {
 *             value: key2,
 *         },
 *     ],
 * }, {
 *     ignoreChanges: ["credentials"],
 * });
 * ```
 */
export class IntegrationCloudflareTokens extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationCloudflareTokens resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationCloudflareTokensState, opts?: pulumi.CustomResourceOptions): IntegrationCloudflareTokens {
        return new IntegrationCloudflareTokens(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationCloudflareTokens:IntegrationCloudflareTokens';

    /**
     * Returns true if the given object is an instance of IntegrationCloudflareTokens.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationCloudflareTokens {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationCloudflareTokens.__pulumiType;
    }

    /**
     * The API Token
     */
    declare public readonly apiToken: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationCloudflareTokens resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationCloudflareTokensArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationCloudflareTokensArgs | IntegrationCloudflareTokensState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationCloudflareTokensState | undefined;
            resourceInputs["apiToken"] = state?.apiToken;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationCloudflareTokensArgs | undefined;
            if (args?.apiToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'apiToken'");
            }
            resourceInputs["apiToken"] = args?.apiToken ? pulumi.secret(args.apiToken) : undefined;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationCloudflareTokens.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationCloudflareTokens resources.
 */
export interface IntegrationCloudflareTokensState {
    /**
     * The API Token
     */
    apiToken?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationCloudflareTokens resource.
 */
export interface IntegrationCloudflareTokensArgs {
    /**
     * The API Token
     */
    apiToken: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
