// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Terraform Cloud Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 * import * as tfe from "@pulumi/tfe";
 *
 * const prod = tfe.Workspace({
 *     name: "my-workspace-name",
 *     organization: "my-org-name",
 * });
 * const prodIntegrationTerraformCloud = new doppler.IntegrationTerraformCloud("prod", {
 *     name: "Production",
 *     apiKey: "my_api_key",
 * });
 * const backendProd = new doppler.SecretsSyncTerraformCloud("backend_prod", {
 *     integration: prodIntegrationTerraformCloud.id,
 *     project: "backend",
 *     config: "prd",
 *     syncTarget: "workspace",
 *     workspaceId: prod.id,
 *     variableSyncType: "terraform",
 *     nameTransform: "lowercase",
 *     deleteBehavior: "leave_in_target",
 * });
 * ```
 */
export class IntegrationTerraformCloud extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationTerraformCloud resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationTerraformCloudState, opts?: pulumi.CustomResourceOptions): IntegrationTerraformCloud {
        return new IntegrationTerraformCloud(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationTerraformCloud:IntegrationTerraformCloud';

    /**
     * Returns true if the given object is an instance of IntegrationTerraformCloud.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationTerraformCloud {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationTerraformCloud.__pulumiType;
    }

    /**
     * A Terraform Cloud API key.
     */
    declare public readonly apiKey: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationTerraformCloud resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationTerraformCloudArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationTerraformCloudArgs | IntegrationTerraformCloudState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationTerraformCloudState | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationTerraformCloudArgs | undefined;
            if (args?.apiKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'apiKey'");
            }
            resourceInputs["apiKey"] = args?.apiKey ? pulumi.secret(args.apiKey) : undefined;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationTerraformCloud.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationTerraformCloud resources.
 */
export interface IntegrationTerraformCloudState {
    /**
     * A Terraform Cloud API key.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationTerraformCloud resource.
 */
export interface IntegrationTerraformCloudArgs {
    /**
     * A Terraform Cloud API key.
     */
    apiKey: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
