// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Fly.io Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const prod = new doppler.IntegrationFlyio("prod", {
 *     name: "TF Fly.io",
 *     apiKey: "fo1_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 * });
 * const backendProd = new doppler.SecretsSyncFlyio("backend_prod", {
 *     integration: prod.id,
 *     project: "backend",
 *     config: "prd",
 *     appId: "my-app",
 *     restartMachines: true,
 *     deleteBehavior: "leave_in_target",
 * });
 * ```
 */
export class IntegrationFlyio extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationFlyio resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationFlyioState, opts?: pulumi.CustomResourceOptions): IntegrationFlyio {
        return new IntegrationFlyio(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationFlyio:IntegrationFlyio';

    /**
     * Returns true if the given object is an instance of IntegrationFlyio.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationFlyio {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationFlyio.__pulumiType;
    }

    /**
     * A Fly.io API key.
     */
    declare public readonly apiKey: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationFlyio resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationFlyioArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationFlyioArgs | IntegrationFlyioState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationFlyioState | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationFlyioArgs | undefined;
            if (args?.apiKey === undefined && !opts.urn) {
                throw new Error("Missing required property 'apiKey'");
            }
            resourceInputs["apiKey"] = args?.apiKey ? pulumi.secret(args.apiKey) : undefined;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(IntegrationFlyio.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationFlyio resources.
 */
export interface IntegrationFlyioState {
    /**
     * A Fly.io API key.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationFlyio resource.
 */
export interface IntegrationFlyioArgs {
    /**
     * A Fly.io API key.
     */
    apiKey: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
