// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a AWS Postgres Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const config = new pulumi.Config();
 * const dbPassword1 = config.get("dbPassword1") || "";
 * const dbPassword2 = config.get("dbPassword2") || "";
 * const iAwsPostgres = new doppler.IntegrationAwsPostgres("i_aws_postgres", {
 *     name: "TF AWS Postgres",
 *     assumeRoleArn: "arn:aws:iam::xxxxxxxxxxxx:role/xxxxxxxxxxxxxxxx",
 *     lambdaArn: "arn:aws:lambda:xxxxxxxxx:xxxxxxxxxxxx:function:xxxxxxxxxxxxxxxxxxxx",
 * });
 * const rsAwsPostgres = new doppler.RotatedSecretAwsPostgres("rs_aws_postgres", {
 *     integration: iAwsPostgres.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "DB",
 *     rotationPeriodSec: 2592000,
 *     host: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 *     port: 5432,
 *     database: "xxxxxxxx",
 *     managingUserUsername: "xxxxxxxx",
 *     managingUserPassword: "xxxxxxxxxxxxxxxxxxxx",
 *     credentials: [
 *         {
 *             username: "xxxxxxxxxxx",
 *             password: dbPassword1,
 *         },
 *         {
 *             username: "xxxxxxxxxxx",
 *             password: dbPassword2,
 *         },
 *     ],
 * }, {
 *     ignoreChanges: ["credentials"],
 * });
 * ```
 */
export class IntegrationAwsPostgres extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationAwsPostgres resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationAwsPostgresState, opts?: pulumi.CustomResourceOptions): IntegrationAwsPostgres {
        return new IntegrationAwsPostgres(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationAwsPostgres:IntegrationAwsPostgres';

    /**
     * Returns true if the given object is an instance of IntegrationAwsPostgres.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationAwsPostgres {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationAwsPostgres.__pulumiType;
    }

    /**
     * IAM Role ARN for role assumption
     */
    declare public readonly assumeRoleArn: pulumi.Output<string>;
    /**
     * The Lambda ARN
     */
    declare public readonly lambdaArn: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationAwsPostgres resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationAwsPostgresArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationAwsPostgresArgs | IntegrationAwsPostgresState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationAwsPostgresState | undefined;
            resourceInputs["assumeRoleArn"] = state?.assumeRoleArn;
            resourceInputs["lambdaArn"] = state?.lambdaArn;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationAwsPostgresArgs | undefined;
            if (args?.assumeRoleArn === undefined && !opts.urn) {
                throw new Error("Missing required property 'assumeRoleArn'");
            }
            if (args?.lambdaArn === undefined && !opts.urn) {
                throw new Error("Missing required property 'lambdaArn'");
            }
            resourceInputs["assumeRoleArn"] = args?.assumeRoleArn;
            resourceInputs["lambdaArn"] = args?.lambdaArn;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationAwsPostgres.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationAwsPostgres resources.
 */
export interface IntegrationAwsPostgresState {
    /**
     * IAM Role ARN for role assumption
     */
    assumeRoleArn?: pulumi.Input<string | undefined>;
    /**
     * The Lambda ARN
     */
    lambdaArn?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationAwsPostgres resource.
 */
export interface IntegrationAwsPostgresArgs {
    /**
     * IAM Role ARN for role assumption
     */
    assumeRoleArn: pulumi.Input<string>;
    /**
     * The Lambda ARN
     */
    lambdaArn: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
