// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a GCP Service Account Keys Doppler integration.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 * import * as gcp from "@pulumi/gcp";
 * import * as std from "@pulumi/std";
 *
 * const iGcpSakExtid = new doppler.IntegrationExternalId("i_gcp_sak_extid", {integrationType: "gcp_service_account_keys"});
 * const gcpsaDopplerImpersonate = new gcp.serviceaccount.Account("gcpsa_doppler_impersonate", {
 *     accountId: "xxxxxxxxxxx",
 *     description: std.format({
 *         input: "doppler_impersonate:%s",
 *         args: [iGcpSakExtid.id],
 *     }).then(invoke => invoke.result),
 *     displayName: "xxxxxxxxxx",
 * });
 * const dopplerRotationImpersonatePolicy = gcp.organizations.getIAMPolicyOutput({
 *     bindings: [
 *         {
 *             role: "roles/iam.serviceAccountViewer",
 *             members: [
 *                 gcpsaDopplerImpersonate.member,
 *                 "serviceAccount:operator@doppler-integrations.iam.gserviceaccount.com",
 *             ],
 *         },
 *         {
 *             role: "roles/iam.serviceAccountTokenCreator",
 *             members: ["serviceAccount:operator@doppler-integrations.iam.gserviceaccount.com"],
 *         },
 *     ],
 * });
 * const gcpPolicyImpersonate = new gcp.serviceaccount.IAMPolicy("gcp_policy_impersonate", {
 *     serviceAccountId: gcpsaDopplerImpersonate.name,
 *     policyData: dopplerRotationImpersonatePolicy.apply(dopplerRotationImpersonatePolicy => dopplerRotationImpersonatePolicy.policyData),
 * });
 * const gcpsaRotated = new gcp.serviceaccount.Account("gcpsa_rotated", {
 *     accountId: "xxxxxxxxxxxxxxxxxx",
 *     displayName: "xxxxxxxxxxxxxxxxxx",
 * });
 * const dopplerRotatedUserPolicy = gcp.organizations.getIAMPolicyOutput({
 *     bindings: [{
 *         role: "roles/iam.serviceAccountKeyAdmin",
 *         members: [gcpsaDopplerImpersonate.member],
 *     }],
 * });
 * const gcpPolicyRotated = new gcp.serviceaccount.IAMPolicy("gcp_policy_rotated", {
 *     serviceAccountId: gcpsaRotated.name,
 *     policyData: dopplerRotatedUserPolicy.apply(dopplerRotatedUserPolicy => dopplerRotatedUserPolicy.policyData),
 * });
 * const iGcpSak = new doppler.IntegrationGcpServiceAccountKeys("i_gcp_sak", {
 *     name: "TF GCP Service Account Keys",
 *     impersonatedServiceAccount: gcpsaDopplerImpersonate.email,
 *     externalId: iGcpSakExtid.id,
 * });
 * const rsGcpsak = new doppler.RotatedSecretGcpServiceAccountKeys("rs_gcpsak", {
 *     integration: iGcpSak.id,
 *     project: "backend",
 *     config: "dev",
 *     name: "GCP_SERVICE_ACCOUNT",
 *     rotationPeriodSec: 2592000,
 *     serviceAccount: gcpsaRotated.email,
 * });
 * ```
 */
export class IntegrationGcpServiceAccountKeys extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationGcpServiceAccountKeys resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationGcpServiceAccountKeysState, opts?: pulumi.CustomResourceOptions): IntegrationGcpServiceAccountKeys {
        return new IntegrationGcpServiceAccountKeys(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/integrationGcpServiceAccountKeys:IntegrationGcpServiceAccountKeys';

    /**
     * Returns true if the given object is an instance of IntegrationGcpServiceAccountKeys.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationGcpServiceAccountKeys {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationGcpServiceAccountKeys.__pulumiType;
    }

    /**
     * The Doppler-generated external id (placed in the service account description field)
     */
    declare public readonly externalId: pulumi.Output<string>;
    /**
     * The service account email of the account to be impersonated
     */
    declare public readonly impersonatedServiceAccount: pulumi.Output<string>;
    /**
     * The name of the integration
     */
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a IntegrationGcpServiceAccountKeys resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IntegrationGcpServiceAccountKeysArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationGcpServiceAccountKeysArgs | IntegrationGcpServiceAccountKeysState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationGcpServiceAccountKeysState | undefined;
            resourceInputs["externalId"] = state?.externalId;
            resourceInputs["impersonatedServiceAccount"] = state?.impersonatedServiceAccount;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as IntegrationGcpServiceAccountKeysArgs | undefined;
            if (args?.externalId === undefined && !opts.urn) {
                throw new Error("Missing required property 'externalId'");
            }
            if (args?.impersonatedServiceAccount === undefined && !opts.urn) {
                throw new Error("Missing required property 'impersonatedServiceAccount'");
            }
            resourceInputs["externalId"] = args?.externalId;
            resourceInputs["impersonatedServiceAccount"] = args?.impersonatedServiceAccount;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationGcpServiceAccountKeys.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationGcpServiceAccountKeys resources.
 */
export interface IntegrationGcpServiceAccountKeysState {
    /**
     * The Doppler-generated external id (placed in the service account description field)
     */
    externalId?: pulumi.Input<string | undefined>;
    /**
     * The service account email of the account to be impersonated
     */
    impersonatedServiceAccount?: pulumi.Input<string | undefined>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationGcpServiceAccountKeys resource.
 */
export interface IntegrationGcpServiceAccountKeysArgs {
    /**
     * The Doppler-generated external id (placed in the service account description field)
     */
    externalId: pulumi.Input<string>;
    /**
     * The service account email of the account to be impersonated
     */
    impersonatedServiceAccount: pulumi.Input<string>;
    /**
     * The name of the integration
     */
    name?: pulumi.Input<string | undefined>;
}
