// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Doppler project group member.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const backendEngineering = new doppler.ProjectMemberGroup("backend_engineering", {
 *     project: "backend",
 *     groupSlug: engineering.slug,
 *     role: "collaborator",
 *     environments: [
 *         "dev",
 *         "stg",
 *     ],
 * });
 * ```
 */
export class ProjectMemberGroup extends pulumi.CustomResource {
    /**
     * Get an existing ProjectMemberGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectMemberGroupState, opts?: pulumi.CustomResourceOptions): ProjectMemberGroup {
        return new ProjectMemberGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/projectMemberGroup:ProjectMemberGroup';

    /**
     * Returns true if the given object is an instance of ProjectMemberGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectMemberGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectMemberGroup.__pulumiType;
    }

    /**
     * The environments in the project where this access will apply (null or omitted for roles with access to all environments)
     */
    declare public readonly environments: pulumi.Output<string[] | undefined>;
    /**
     * The slug of the Doppler group
     */
    declare public readonly groupSlug: pulumi.Output<string>;
    /**
     * The name of the Doppler project where the access is applied
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * The project role identifier for the access. Must use either one of the built-in project role slugs (`admin`, `owner`, `collaborator`, or `noAccess`), or the slug for a custom project role.
     */
    declare public readonly role: pulumi.Output<string>;

    /**
     * Create a ProjectMemberGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectMemberGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectMemberGroupArgs | ProjectMemberGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectMemberGroupState | undefined;
            resourceInputs["environments"] = state?.environments;
            resourceInputs["groupSlug"] = state?.groupSlug;
            resourceInputs["project"] = state?.project;
            resourceInputs["role"] = state?.role;
        } else {
            const args = argsOrState as ProjectMemberGroupArgs | undefined;
            if (args?.groupSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'groupSlug'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            resourceInputs["environments"] = args?.environments;
            resourceInputs["groupSlug"] = args?.groupSlug;
            resourceInputs["project"] = args?.project;
            resourceInputs["role"] = args?.role;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectMemberGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProjectMemberGroup resources.
 */
export interface ProjectMemberGroupState {
    /**
     * The environments in the project where this access will apply (null or omitted for roles with access to all environments)
     */
    environments?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The slug of the Doppler group
     */
    groupSlug?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project where the access is applied
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * The project role identifier for the access. Must use either one of the built-in project role slugs (`admin`, `owner`, `collaborator`, or `noAccess`), or the slug for a custom project role.
     */
    role?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProjectMemberGroup resource.
 */
export interface ProjectMemberGroupArgs {
    /**
     * The environments in the project where this access will apply (null or omitted for roles with access to all environments)
     */
    environments?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The slug of the Doppler group
     */
    groupSlug: pulumi.Input<string>;
    /**
     * The name of the Doppler project where the access is applied
     */
    project: pulumi.Input<string>;
    /**
     * The project role identifier for the access. Must use either one of the built-in project role slugs (`admin`, `owner`, `collaborator`, or `noAccess`), or the slug for a custom project role.
     */
    role: pulumi.Input<string>;
}
