// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Doppler project user member.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const brian = doppler.getUser({
 *     email: "brian@doppler.com",
 * });
 * const backendBrian = new doppler.ProjectMemberUser("backend_brian", {
 *     project: "backend",
 *     userSlug: brian.then(brian => brian.slug),
 *     role: "collaborator",
 *     environments: [
 *         "dev",
 *         "stg",
 *     ],
 * });
 * ```
 */
export class ProjectMemberUser extends pulumi.CustomResource {
    /**
     * Get an existing ProjectMemberUser resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectMemberUserState, opts?: pulumi.CustomResourceOptions): ProjectMemberUser {
        return new ProjectMemberUser(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/projectMemberUser:ProjectMemberUser';

    /**
     * Returns true if the given object is an instance of ProjectMemberUser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectMemberUser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectMemberUser.__pulumiType;
    }

    /**
     * The environments in the project where this access will apply (null or omitted for roles with access to all environments)
     */
    declare public readonly environments: pulumi.Output<string[] | undefined>;
    /**
     * The name of the Doppler project where the access is applied
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * The project role identifier for the access. Must use either one of the built-in project role slugs (`admin`, `owner`, `collaborator`, or `noAccess`), or the slug for a custom project role.
     */
    declare public readonly role: pulumi.Output<string>;
    /**
     * The slug of the Doppler workplace user
     */
    declare public readonly userSlug: pulumi.Output<string>;

    /**
     * Create a ProjectMemberUser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectMemberUserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectMemberUserArgs | ProjectMemberUserState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectMemberUserState | undefined;
            resourceInputs["environments"] = state?.environments;
            resourceInputs["project"] = state?.project;
            resourceInputs["role"] = state?.role;
            resourceInputs["userSlug"] = state?.userSlug;
        } else {
            const args = argsOrState as ProjectMemberUserArgs | undefined;
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.role === undefined && !opts.urn) {
                throw new Error("Missing required property 'role'");
            }
            if (args?.userSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'userSlug'");
            }
            resourceInputs["environments"] = args?.environments;
            resourceInputs["project"] = args?.project;
            resourceInputs["role"] = args?.role;
            resourceInputs["userSlug"] = args?.userSlug;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectMemberUser.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProjectMemberUser resources.
 */
export interface ProjectMemberUserState {
    /**
     * The environments in the project where this access will apply (null or omitted for roles with access to all environments)
     */
    environments?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name of the Doppler project where the access is applied
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * The project role identifier for the access. Must use either one of the built-in project role slugs (`admin`, `owner`, `collaborator`, or `noAccess`), or the slug for a custom project role.
     */
    role?: pulumi.Input<string | undefined>;
    /**
     * The slug of the Doppler workplace user
     */
    userSlug?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProjectMemberUser resource.
 */
export interface ProjectMemberUserArgs {
    /**
     * The environments in the project where this access will apply (null or omitted for roles with access to all environments)
     */
    environments?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name of the Doppler project where the access is applied
     */
    project: pulumi.Input<string>;
    /**
     * The project role identifier for the access. Must use either one of the built-in project role slugs (`admin`, `owner`, `collaborator`, or `noAccess`), or the slug for a custom project role.
     */
    role: pulumi.Input<string>;
    /**
     * The slug of the Doppler workplace user
     */
    userSlug: pulumi.Input<string>;
}
