// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the doppler package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'doppler';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * A Doppler token, either a personal or service token. This can also be set via the DOPPLER_TOKEN environment variable. Only one of `dopplerToken` or OIDC authentication (`oidcIdentity` + `oidcToken`/`oidcTokenFile`) may be specified.
     */
    declare public readonly dopplerToken: pulumi.Output<string | undefined>;
    /**
     * The Doppler API host (i.e. https://api.doppler.com). This can also be set via the DOPPLER_API_HOST environment variable.
     */
    declare public readonly host: pulumi.Output<string | undefined>;
    /**
     * The identity ID (UUID) of the Doppler service account identity for OIDC authentication. This can also be set via the DOPPLER_OIDC_IDENTITY environment variable.
     */
    declare public readonly oidcIdentity: pulumi.Output<string | undefined>;
    /**
     * A JWT token to use for OIDC authentication. Only one of `oidcToken` or `oidcTokenFile` may be set. This can also be set via the DOPPLER_OIDC_TOKEN environment variable.
     */
    declare public readonly oidcToken: pulumi.Output<string | undefined>;
    /**
     * A path to a file containing a JWT token for OIDC authentication (e.g. a Kubernetes projected service account token). Only one of `oidcToken` or `oidcTokenFile` may be set. This can also be set via the DOPPLER_OIDC_TOKEN_FILE environment variable.
     */
    declare public readonly oidcTokenFile: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["dopplerToken"] = (args?.dopplerToken) ?? utilities.getEnv("DOPPLER_TOKEN");
            resourceInputs["host"] = (args?.host) ?? utilities.getEnv("DOPPLER_API_HOST");
            resourceInputs["oidcIdentity"] = args?.oidcIdentity;
            resourceInputs["oidcToken"] = args?.oidcToken ? pulumi.secret(args.oidcToken) : undefined;
            resourceInputs["oidcTokenFile"] = args?.oidcTokenFile;
            resourceInputs["verifyTls"] = pulumi.output((args?.verifyTls) ?? utilities.getEnvBoolean("DOPPLER_VERIFY_TLS")).apply(JSON.stringify);
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["oidcToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<Provider.TerraformConfigResult> {
        return pulumi.runtime.call("pulumi:providers:doppler/terraformConfig", {
            "__self__": this,
        }, this);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * A Doppler token, either a personal or service token. This can also be set via the DOPPLER_TOKEN environment variable. Only one of `dopplerToken` or OIDC authentication (`oidcIdentity` + `oidcToken`/`oidcTokenFile`) may be specified.
     */
    dopplerToken?: pulumi.Input<string | undefined>;
    /**
     * The Doppler API host (i.e. https://api.doppler.com). This can also be set via the DOPPLER_API_HOST environment variable.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * The identity ID (UUID) of the Doppler service account identity for OIDC authentication. This can also be set via the DOPPLER_OIDC_IDENTITY environment variable.
     */
    oidcIdentity?: pulumi.Input<string | undefined>;
    /**
     * A JWT token to use for OIDC authentication. Only one of `oidcToken` or `oidcTokenFile` may be set. This can also be set via the DOPPLER_OIDC_TOKEN environment variable.
     */
    oidcToken?: pulumi.Input<string | undefined>;
    /**
     * A path to a file containing a JWT token for OIDC authentication (e.g. a Kubernetes projected service account token). Only one of `oidcToken` or `oidcTokenFile` may be set. This can also be set via the DOPPLER_OIDC_TOKEN_FILE environment variable.
     */
    oidcTokenFile?: pulumi.Input<string | undefined>;
    /**
     * Whether or not to verify TLS. This can also be set via the DOPPLER_VERIFY_TLS environment variable.
     */
    verifyTls?: pulumi.Input<boolean | undefined>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
