// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class RotatedSecretCloudflareTokens extends pulumi.CustomResource {
    /**
     * Get an existing RotatedSecretCloudflareTokens resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RotatedSecretCloudflareTokensState, opts?: pulumi.CustomResourceOptions): RotatedSecretCloudflareTokens {
        return new RotatedSecretCloudflareTokens(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/rotatedSecretCloudflareTokens:RotatedSecretCloudflareTokens';

    /**
     * Returns true if the given object is an instance of RotatedSecretCloudflareTokens.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RotatedSecretCloudflareTokens {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RotatedSecretCloudflareTokens.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * Rotated secret credentials
     */
    declare public readonly credentials: pulumi.Output<outputs.RotatedSecretCloudflareTokensCredential[]>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * The name of the rotated secret
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The name of the Doppler project
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * How frequently to rotate the secret
     */
    declare public readonly rotationPeriodSec: pulumi.Output<number>;

    /**
     * Create a RotatedSecretCloudflareTokens resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RotatedSecretCloudflareTokensArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RotatedSecretCloudflareTokensArgs | RotatedSecretCloudflareTokensState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RotatedSecretCloudflareTokensState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["credentials"] = state?.credentials;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["name"] = state?.name;
            resourceInputs["project"] = state?.project;
            resourceInputs["rotationPeriodSec"] = state?.rotationPeriodSec;
        } else {
            const args = argsOrState as RotatedSecretCloudflareTokensArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.credentials === undefined && !opts.urn) {
                throw new Error("Missing required property 'credentials'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.rotationPeriodSec === undefined && !opts.urn) {
                throw new Error("Missing required property 'rotationPeriodSec'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["credentials"] = args?.credentials;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["name"] = args?.name;
            resourceInputs["project"] = args?.project;
            resourceInputs["rotationPeriodSec"] = args?.rotationPeriodSec;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RotatedSecretCloudflareTokens.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RotatedSecretCloudflareTokens resources.
 */
export interface RotatedSecretCloudflareTokensState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * Rotated secret credentials
     */
    credentials?: pulumi.Input<pulumi.Input<inputs.RotatedSecretCloudflareTokensCredential>[] | undefined>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * The name of the rotated secret
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * How frequently to rotate the secret
     */
    rotationPeriodSec?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a RotatedSecretCloudflareTokens resource.
 */
export interface RotatedSecretCloudflareTokensArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * Rotated secret credentials
     */
    credentials: pulumi.Input<pulumi.Input<inputs.RotatedSecretCloudflareTokensCredential>[]>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    integration: pulumi.Input<string>;
    /**
     * The name of the rotated secret
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project: pulumi.Input<string>;
    /**
     * How frequently to rotate the secret
     */
    rotationPeriodSec: pulumi.Input<number>;
}
