// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RotatedSecretAwsIamUserKeys extends pulumi.CustomResource {
    /**
     * Get an existing RotatedSecretAwsIamUserKeys resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RotatedSecretAwsIamUserKeysState, opts?: pulumi.CustomResourceOptions): RotatedSecretAwsIamUserKeys {
        return new RotatedSecretAwsIamUserKeys(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/rotatedSecretAwsIamUserKeys:RotatedSecretAwsIamUserKeys';

    /**
     * Returns true if the given object is an instance of RotatedSecretAwsIamUserKeys.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RotatedSecretAwsIamUserKeys {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RotatedSecretAwsIamUserKeys.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * The name of the rotated secret
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The name of the Doppler project
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * How frequently to rotate the secret
     */
    declare public readonly rotationPeriodSec: pulumi.Output<number>;
    /**
     * The IAM username (excluding ARN and scope prefix)
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a RotatedSecretAwsIamUserKeys resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RotatedSecretAwsIamUserKeysArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RotatedSecretAwsIamUserKeysArgs | RotatedSecretAwsIamUserKeysState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RotatedSecretAwsIamUserKeysState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["name"] = state?.name;
            resourceInputs["project"] = state?.project;
            resourceInputs["rotationPeriodSec"] = state?.rotationPeriodSec;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as RotatedSecretAwsIamUserKeysArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.rotationPeriodSec === undefined && !opts.urn) {
                throw new Error("Missing required property 'rotationPeriodSec'");
            }
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["name"] = args?.name;
            resourceInputs["project"] = args?.project;
            resourceInputs["rotationPeriodSec"] = args?.rotationPeriodSec;
            resourceInputs["username"] = args?.username;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RotatedSecretAwsIamUserKeys.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RotatedSecretAwsIamUserKeys resources.
 */
export interface RotatedSecretAwsIamUserKeysState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * The name of the rotated secret
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * How frequently to rotate the secret
     */
    rotationPeriodSec?: pulumi.Input<number | undefined>;
    /**
     * The IAM username (excluding ARN and scope prefix)
     */
    username?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a RotatedSecretAwsIamUserKeys resource.
 */
export interface RotatedSecretAwsIamUserKeysArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    integration: pulumi.Input<string>;
    /**
     * The name of the rotated secret
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project: pulumi.Input<string>;
    /**
     * How frequently to rotate the secret
     */
    rotationPeriodSec: pulumi.Input<number>;
    /**
     * The IAM username (excluding ARN and scope prefix)
     */
    username: pulumi.Input<string>;
}
