// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class RotatedSecretAwsMysql extends pulumi.CustomResource {
    /**
     * Get an existing RotatedSecretAwsMysql resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RotatedSecretAwsMysqlState, opts?: pulumi.CustomResourceOptions): RotatedSecretAwsMysql {
        return new RotatedSecretAwsMysql(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/rotatedSecretAwsMysql:RotatedSecretAwsMysql';

    /**
     * Returns true if the given object is an instance of RotatedSecretAwsMysql.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RotatedSecretAwsMysql {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RotatedSecretAwsMysql.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * Rotated secret credentials
     */
    declare public readonly credentials: pulumi.Output<outputs.RotatedSecretAwsMysqlCredential[]>;
    /**
     * The DB database
     */
    declare public readonly database: pulumi.Output<string | undefined>;
    /**
     * The DB Host
     */
    declare public readonly host: pulumi.Output<string>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * The managing user password
     */
    declare public readonly managingUserPassword: pulumi.Output<string>;
    /**
     * The managing user username
     */
    declare public readonly managingUserUsername: pulumi.Output<string>;
    /**
     * The name of the rotated secret
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The DB Port
     */
    declare public readonly port: pulumi.Output<number>;
    /**
     * The name of the Doppler project
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * How frequently to rotate the secret
     */
    declare public readonly rotationPeriodSec: pulumi.Output<number>;

    /**
     * Create a RotatedSecretAwsMysql resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RotatedSecretAwsMysqlArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RotatedSecretAwsMysqlArgs | RotatedSecretAwsMysqlState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RotatedSecretAwsMysqlState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["credentials"] = state?.credentials;
            resourceInputs["database"] = state?.database;
            resourceInputs["host"] = state?.host;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["managingUserPassword"] = state?.managingUserPassword;
            resourceInputs["managingUserUsername"] = state?.managingUserUsername;
            resourceInputs["name"] = state?.name;
            resourceInputs["port"] = state?.port;
            resourceInputs["project"] = state?.project;
            resourceInputs["rotationPeriodSec"] = state?.rotationPeriodSec;
        } else {
            const args = argsOrState as RotatedSecretAwsMysqlArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.credentials === undefined && !opts.urn) {
                throw new Error("Missing required property 'credentials'");
            }
            if (args?.host === undefined && !opts.urn) {
                throw new Error("Missing required property 'host'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.managingUserPassword === undefined && !opts.urn) {
                throw new Error("Missing required property 'managingUserPassword'");
            }
            if (args?.managingUserUsername === undefined && !opts.urn) {
                throw new Error("Missing required property 'managingUserUsername'");
            }
            if (args?.port === undefined && !opts.urn) {
                throw new Error("Missing required property 'port'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.rotationPeriodSec === undefined && !opts.urn) {
                throw new Error("Missing required property 'rotationPeriodSec'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["credentials"] = args?.credentials;
            resourceInputs["database"] = args?.database;
            resourceInputs["host"] = args?.host;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["managingUserPassword"] = args?.managingUserPassword ? pulumi.secret(args.managingUserPassword) : undefined;
            resourceInputs["managingUserUsername"] = args?.managingUserUsername;
            resourceInputs["name"] = args?.name;
            resourceInputs["port"] = args?.port;
            resourceInputs["project"] = args?.project;
            resourceInputs["rotationPeriodSec"] = args?.rotationPeriodSec;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["managingUserPassword"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(RotatedSecretAwsMysql.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RotatedSecretAwsMysql resources.
 */
export interface RotatedSecretAwsMysqlState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * Rotated secret credentials
     */
    credentials?: pulumi.Input<pulumi.Input<inputs.RotatedSecretAwsMysqlCredential>[] | undefined>;
    /**
     * The DB database
     */
    database?: pulumi.Input<string | undefined>;
    /**
     * The DB Host
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * The managing user password
     */
    managingUserPassword?: pulumi.Input<string | undefined>;
    /**
     * The managing user username
     */
    managingUserUsername?: pulumi.Input<string | undefined>;
    /**
     * The name of the rotated secret
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The DB Port
     */
    port?: pulumi.Input<number | undefined>;
    /**
     * The name of the Doppler project
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * How frequently to rotate the secret
     */
    rotationPeriodSec?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a RotatedSecretAwsMysql resource.
 */
export interface RotatedSecretAwsMysqlArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * Rotated secret credentials
     */
    credentials: pulumi.Input<pulumi.Input<inputs.RotatedSecretAwsMysqlCredential>[]>;
    /**
     * The DB database
     */
    database?: pulumi.Input<string | undefined>;
    /**
     * The DB Host
     */
    host: pulumi.Input<string>;
    /**
     * The slug of the integration to use for this rotated secret
     */
    integration: pulumi.Input<string>;
    /**
     * The managing user password
     */
    managingUserPassword: pulumi.Input<string>;
    /**
     * The managing user username
     */
    managingUserUsername: pulumi.Input<string>;
    /**
     * The name of the rotated secret
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The DB Port
     */
    port: pulumi.Input<number>;
    /**
     * The name of the Doppler project
     */
    project: pulumi.Input<string>;
    /**
     * How frequently to rotate the secret
     */
    rotationPeriodSec: pulumi.Input<number>;
}
