// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a CircleCI Doppler sync.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const prod = new doppler.IntegrationCircleci("prod", {
 *     name: "Production",
 *     apiToken: "my_api_token",
 * });
 * const backendProd = new doppler.SecretsSyncCircleci("backend_prod", {
 *     integration: prod.id,
 *     project: "backend",
 *     config: "prd",
 *     resourceType: "project",
 *     resourceId: "github/myorg/myproject",
 *     organizationSlug: "myorg",
 *     deleteBehavior: "leave_in_target",
 * });
 * ```
 */
export class SecretsSyncCircleci extends pulumi.CustomResource {
    /**
     * Get an existing SecretsSyncCircleci resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretsSyncCircleciState, opts?: pulumi.CustomResourceOptions): SecretsSyncCircleci {
        return new SecretsSyncCircleci(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/secretsSyncCircleci:SecretsSyncCircleci';

    /**
     * Returns true if the given object is an instance of SecretsSyncCircleci.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretsSyncCircleci {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretsSyncCircleci.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    declare public readonly deleteBehavior: pulumi.Output<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * The organization slug where the resource is located
     */
    declare public readonly organizationSlug: pulumi.Output<string>;
    /**
     * The name of the Doppler project
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * The resource ID (either project or context) to sync to
     */
    declare public readonly resourceId: pulumi.Output<string>;
    /**
     * Either "project" or "context", based on the resource type to sync to
     */
    declare public readonly resourceType: pulumi.Output<string>;

    /**
     * Create a SecretsSyncCircleci resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretsSyncCircleciArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretsSyncCircleciArgs | SecretsSyncCircleciState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretsSyncCircleciState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["deleteBehavior"] = state?.deleteBehavior;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["organizationSlug"] = state?.organizationSlug;
            resourceInputs["project"] = state?.project;
            resourceInputs["resourceId"] = state?.resourceId;
            resourceInputs["resourceType"] = state?.resourceType;
        } else {
            const args = argsOrState as SecretsSyncCircleciArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.organizationSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationSlug'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.resourceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceId'");
            }
            if (args?.resourceType === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceType'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["deleteBehavior"] = args?.deleteBehavior;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["organizationSlug"] = args?.organizationSlug;
            resourceInputs["project"] = args?.project;
            resourceInputs["resourceId"] = args?.resourceId;
            resourceInputs["resourceType"] = args?.resourceType;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretsSyncCircleci.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretsSyncCircleci resources.
 */
export interface SecretsSyncCircleciState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * The organization slug where the resource is located
     */
    organizationSlug?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * The resource ID (either project or context) to sync to
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * Either "project" or "context", based on the resource type to sync to
     */
    resourceType?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SecretsSyncCircleci resource.
 */
export interface SecretsSyncCircleciArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration: pulumi.Input<string>;
    /**
     * The organization slug where the resource is located
     */
    organizationSlug: pulumi.Input<string>;
    /**
     * The name of the Doppler project
     */
    project: pulumi.Input<string>;
    /**
     * The resource ID (either project or context) to sync to
     */
    resourceId: pulumi.Input<string>;
    /**
     * Either "project" or "context", based on the resource type to sync to
     */
    resourceType: pulumi.Input<string>;
}
