// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an Azure Vault Doppler sync.
 */
export class SecretsSyncAzureVault extends pulumi.CustomResource {
    /**
     * Get an existing SecretsSyncAzureVault resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretsSyncAzureVaultState, opts?: pulumi.CustomResourceOptions): SecretsSyncAzureVault {
        return new SecretsSyncAzureVault(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/secretsSyncAzureVault:SecretsSyncAzureVault';

    /**
     * Returns true if the given object is an instance of SecretsSyncAzureVault.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretsSyncAzureVault {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretsSyncAzureVault.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    declare public readonly deleteBehavior: pulumi.Output<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * The name of the Doppler project
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * The name of the secret being synced to when using the "single-secret" sync strategy. Required when using "single-secret" sync strategy.
     */
    declare public readonly singleSecretName: pulumi.Output<string | undefined>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`).
     */
    declare public readonly syncStrategy: pulumi.Output<string>;
    /**
     * The Azure Vault URI for the vault secrets will be synced to.
     */
    declare public readonly vaultUri: pulumi.Output<string>;

    /**
     * Create a SecretsSyncAzureVault resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretsSyncAzureVaultArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretsSyncAzureVaultArgs | SecretsSyncAzureVaultState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretsSyncAzureVaultState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["deleteBehavior"] = state?.deleteBehavior;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["project"] = state?.project;
            resourceInputs["singleSecretName"] = state?.singleSecretName;
            resourceInputs["syncStrategy"] = state?.syncStrategy;
            resourceInputs["vaultUri"] = state?.vaultUri;
        } else {
            const args = argsOrState as SecretsSyncAzureVaultArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.syncStrategy === undefined && !opts.urn) {
                throw new Error("Missing required property 'syncStrategy'");
            }
            if (args?.vaultUri === undefined && !opts.urn) {
                throw new Error("Missing required property 'vaultUri'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["deleteBehavior"] = args?.deleteBehavior;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["project"] = args?.project;
            resourceInputs["singleSecretName"] = args?.singleSecretName;
            resourceInputs["syncStrategy"] = args?.syncStrategy;
            resourceInputs["vaultUri"] = args?.vaultUri;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretsSyncAzureVault.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretsSyncAzureVault resources.
 */
export interface SecretsSyncAzureVaultState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * The name of the secret being synced to when using the "single-secret" sync strategy. Required when using "single-secret" sync strategy.
     */
    singleSecretName?: pulumi.Input<string | undefined>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`).
     */
    syncStrategy?: pulumi.Input<string | undefined>;
    /**
     * The Azure Vault URI for the vault secrets will be synced to.
     */
    vaultUri?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SecretsSyncAzureVault resource.
 */
export interface SecretsSyncAzureVaultArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration: pulumi.Input<string>;
    /**
     * The name of the Doppler project
     */
    project: pulumi.Input<string>;
    /**
     * The name of the secret being synced to when using the "single-secret" sync strategy. Required when using "single-secret" sync strategy.
     */
    singleSecretName?: pulumi.Input<string | undefined>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`).
     */
    syncStrategy: pulumi.Input<string>;
    /**
     * The Azure Vault URI for the vault secrets will be synced to.
     */
    vaultUri: pulumi.Input<string>;
}
