// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a GCP Secret Manager Doppler sync.
 */
export class SecretsSyncGcpSecretManager extends pulumi.CustomResource {
    /**
     * Get an existing SecretsSyncGcpSecretManager resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretsSyncGcpSecretManagerState, opts?: pulumi.CustomResourceOptions): SecretsSyncGcpSecretManager {
        return new SecretsSyncGcpSecretManager(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/secretsSyncGcpSecretManager:SecretsSyncGcpSecretManager';

    /**
     * Returns true if the given object is an instance of SecretsSyncGcpSecretManager.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretsSyncGcpSecretManager {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretsSyncGcpSecretManager.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    declare public readonly deleteBehavior: pulumi.Output<string | undefined>;
    /**
     * Specifies the format secrets will be stored in. Either `env` or `json`. Defaults to `json`.
     */
    declare public readonly format: pulumi.Output<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * The name used to store the secret when syncStrategy is set to `single-secret` (note that the integration's `gcpSecretPrefix` will be prepended to this).
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The name of the Doppler project
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * The GCP regions used for replication. Can include any supported GCP region or `["automatic"]`.
     */
    declare public readonly regions: pulumi.Output<string[]>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`).
     */
    declare public readonly syncStrategy: pulumi.Output<string>;

    /**
     * Create a SecretsSyncGcpSecretManager resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretsSyncGcpSecretManagerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretsSyncGcpSecretManagerArgs | SecretsSyncGcpSecretManagerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretsSyncGcpSecretManagerState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["deleteBehavior"] = state?.deleteBehavior;
            resourceInputs["format"] = state?.format;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["name"] = state?.name;
            resourceInputs["project"] = state?.project;
            resourceInputs["regions"] = state?.regions;
            resourceInputs["syncStrategy"] = state?.syncStrategy;
        } else {
            const args = argsOrState as SecretsSyncGcpSecretManagerArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.regions === undefined && !opts.urn) {
                throw new Error("Missing required property 'regions'");
            }
            if (args?.syncStrategy === undefined && !opts.urn) {
                throw new Error("Missing required property 'syncStrategy'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["deleteBehavior"] = args?.deleteBehavior;
            resourceInputs["format"] = args?.format;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["name"] = args?.name;
            resourceInputs["project"] = args?.project;
            resourceInputs["regions"] = args?.regions;
            resourceInputs["syncStrategy"] = args?.syncStrategy;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretsSyncGcpSecretManager.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretsSyncGcpSecretManager resources.
 */
export interface SecretsSyncGcpSecretManagerState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * Specifies the format secrets will be stored in. Either `env` or `json`. Defaults to `json`.
     */
    format?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * The name used to store the secret when syncStrategy is set to `single-secret` (note that the integration's `gcpSecretPrefix` will be prepended to this).
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * The GCP regions used for replication. Can include any supported GCP region or `["automatic"]`.
     */
    regions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`).
     */
    syncStrategy?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SecretsSyncGcpSecretManager resource.
 */
export interface SecretsSyncGcpSecretManagerArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * Specifies the format secrets will be stored in. Either `env` or `json`. Defaults to `json`.
     */
    format?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration: pulumi.Input<string>;
    /**
     * The name used to store the secret when syncStrategy is set to `single-secret` (note that the integration's `gcpSecretPrefix` will be prepended to this).
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project: pulumi.Input<string>;
    /**
     * The GCP regions used for replication. Can include any supported GCP region or `["automatic"]`.
     */
    regions: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`).
     */
    syncStrategy: pulumi.Input<string>;
}
