// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a GitHub Copilot Agents Doppler sync.
 */
export class SecretsSyncGithubAgents extends pulumi.CustomResource {
    /**
     * Get an existing SecretsSyncGithubAgents resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretsSyncGithubAgentsState, opts?: pulumi.CustomResourceOptions): SecretsSyncGithubAgents {
        return new SecretsSyncGithubAgents(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/secretsSyncGithubAgents:SecretsSyncGithubAgents';

    /**
     * Returns true if the given object is an instance of SecretsSyncGithubAgents.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretsSyncGithubAgents {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretsSyncGithubAgents.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    declare public readonly deleteBehavior: pulumi.Output<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * Either "all" or "private", based on the which repos you want to have access (only used when `syncTarget` is set to "org")
     */
    declare public readonly orgScope: pulumi.Output<string | undefined>;
    /**
     * The name of the Doppler project
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * The GitHub repo name to sync to (only used when `syncTarget` is set to "repo")
     */
    declare public readonly repoName: pulumi.Output<string | undefined>;
    /**
     * Either "repo" or "org", based on the resource type to sync to
     */
    declare public readonly syncTarget: pulumi.Output<string>;
    /**
     * When enabled, causes secrets with the `unmasked` visibility type to get synced as GitHub Copilot Agents Variables. Defaults to `false`.
     */
    declare public readonly syncUnmaskedAsVariables: pulumi.Output<boolean | undefined>;

    /**
     * Create a SecretsSyncGithubAgents resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretsSyncGithubAgentsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretsSyncGithubAgentsArgs | SecretsSyncGithubAgentsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretsSyncGithubAgentsState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["deleteBehavior"] = state?.deleteBehavior;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["orgScope"] = state?.orgScope;
            resourceInputs["project"] = state?.project;
            resourceInputs["repoName"] = state?.repoName;
            resourceInputs["syncTarget"] = state?.syncTarget;
            resourceInputs["syncUnmaskedAsVariables"] = state?.syncUnmaskedAsVariables;
        } else {
            const args = argsOrState as SecretsSyncGithubAgentsArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.syncTarget === undefined && !opts.urn) {
                throw new Error("Missing required property 'syncTarget'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["deleteBehavior"] = args?.deleteBehavior;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["orgScope"] = args?.orgScope;
            resourceInputs["project"] = args?.project;
            resourceInputs["repoName"] = args?.repoName;
            resourceInputs["syncTarget"] = args?.syncTarget;
            resourceInputs["syncUnmaskedAsVariables"] = args?.syncUnmaskedAsVariables;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretsSyncGithubAgents.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretsSyncGithubAgents resources.
 */
export interface SecretsSyncGithubAgentsState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * Either "all" or "private", based on the which repos you want to have access (only used when `syncTarget` is set to "org")
     */
    orgScope?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * The GitHub repo name to sync to (only used when `syncTarget` is set to "repo")
     */
    repoName?: pulumi.Input<string | undefined>;
    /**
     * Either "repo" or "org", based on the resource type to sync to
     */
    syncTarget?: pulumi.Input<string | undefined>;
    /**
     * When enabled, causes secrets with the `unmasked` visibility type to get synced as GitHub Copilot Agents Variables. Defaults to `false`.
     */
    syncUnmaskedAsVariables?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a SecretsSyncGithubAgents resource.
 */
export interface SecretsSyncGithubAgentsArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration: pulumi.Input<string>;
    /**
     * Either "all" or "private", based on the which repos you want to have access (only used when `syncTarget` is set to "org")
     */
    orgScope?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project: pulumi.Input<string>;
    /**
     * The GitHub repo name to sync to (only used when `syncTarget` is set to "repo")
     */
    repoName?: pulumi.Input<string | undefined>;
    /**
     * Either "repo" or "org", based on the resource type to sync to
     */
    syncTarget: pulumi.Input<string>;
    /**
     * When enabled, causes secrets with the `unmasked` visibility type to get synced as GitHub Copilot Agents Variables. Defaults to `false`.
     */
    syncUnmaskedAsVariables?: pulumi.Input<boolean | undefined>;
}
