// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage the note attached to a Doppler secret. Notes are scoped per project and secret name, and they apply across all configs in the project.
 *
 * The note resource is independent of `doppler.Secret`. A note can be declared for a secret managed inside or outside Terraform, as long as the secret exists in at least one config in the project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const stripeKey = new doppler.SecretNote("stripe_key", {
 *     project: "backend",
 *     name: "STRIPE_SECRET_KEY",
 *     note: "Owner: payments team. Rotate quarterly via Stripe dashboard.",
 * });
 * ```
 */
export class SecretNote extends pulumi.CustomResource {
    /**
     * Get an existing SecretNote resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretNoteState, opts?: pulumi.CustomResourceOptions): SecretNote {
        return new SecretNote(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/secretNote:SecretNote';

    /**
     * Returns true if the given object is an instance of SecretNote.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretNote {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretNote.__pulumiType;
    }

    /**
     * The name of the secret. Notes are scoped per project + secret name and apply across all configs.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The note content to attach to the secret
     */
    declare public readonly note: pulumi.Output<string>;
    /**
     * The name of the Doppler project that owns the secret
     */
    declare public readonly project: pulumi.Output<string>;

    /**
     * Create a SecretNote resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretNoteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretNoteArgs | SecretNoteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretNoteState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["note"] = state?.note;
            resourceInputs["project"] = state?.project;
        } else {
            const args = argsOrState as SecretNoteArgs | undefined;
            if (args?.note === undefined && !opts.urn) {
                throw new Error("Missing required property 'note'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["note"] = args?.note;
            resourceInputs["project"] = args?.project;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretNote.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretNote resources.
 */
export interface SecretNoteState {
    /**
     * The name of the secret. Notes are scoped per project + secret name and apply across all configs.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The note content to attach to the secret
     */
    note?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project that owns the secret
     */
    project?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SecretNote resource.
 */
export interface SecretNoteArgs {
    /**
     * The name of the secret. Notes are scoped per project + secret name and apply across all configs.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The note content to attach to the secret
     */
    note: pulumi.Input<string>;
    /**
     * The name of the Doppler project that owns the secret
     */
    project: pulumi.Input<string>;
}
