// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage an AWS Secrets Manager Doppler sync.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const dopplerSecretsManager = new aws.iam.Role("doppler_secrets_manager", {
 *     name: "doppler_secrets_manager",
 *     assumeRolePolicy: JSON.stringify({
 *         Version: "2012-10-17",
 *         Statement: [{
 *             Effect: "Allow",
 *             Action: "sts:AssumeRole",
 *             Principal: {
 *                 AWS: "arn:aws:iam::299900769157:user/doppler-integration-operator",
 *             },
 *             Condition: {
 *                 StringEquals: {
 *                     "sts:ExternalId": "<YOUR_WORKPLACE_SLUG>",
 *                 },
 *             },
 *         }],
 *     }),
 *     inlinePolicies: [{
 *         name: "doppler_secret_manager",
 *         policy: JSON.stringify({
 *             Version: "2012-10-17",
 *             Statement: [{
 *                 Action: [
 *                     "secretsmanager:GetSecretValue",
 *                     "secretsmanager:DescribeSecret",
 *                     "secretsmanager:PutSecretValue",
 *                     "secretsmanager:CreateSecret",
 *                     "secretsmanager:DeleteSecret",
 *                     "secretsmanager:TagResource",
 *                     "secretsmanager:UpdateSecret",
 *                 ],
 *                 Effect: "Allow",
 *                 Resource: "*",
 *             }],
 *         }),
 *     }],
 * });
 * const prod = new doppler.IntegrationAwsSecretsManager("prod", {
 *     name: "Production",
 *     assumeRoleArn: dopplerSecretsManager.arn,
 * });
 * const backendProd = new doppler.SecretsSyncAwsSecretsManager("backend_prod", {
 *     integration: prod.id,
 *     project: "backend",
 *     config: "prd",
 *     region: "us-east-1",
 *     path: "/backend/",
 *     tags: {
 *         myTag: "enabled",
 *     },
 *     deleteBehavior: "leave_in_target",
 * });
 * ```
 */
export class SecretsSyncAwsSecretsManager extends pulumi.CustomResource {
    /**
     * Get an existing SecretsSyncAwsSecretsManager resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretsSyncAwsSecretsManagerState, opts?: pulumi.CustomResourceOptions): SecretsSyncAwsSecretsManager {
        return new SecretsSyncAwsSecretsManager(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/secretsSyncAwsSecretsManager:SecretsSyncAwsSecretsManager';

    /**
     * Returns true if the given object is an instance of SecretsSyncAwsSecretsManager.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretsSyncAwsSecretsManager {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretsSyncAwsSecretsManager.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    declare public readonly deleteBehavior: pulumi.Output<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    declare public readonly integration: pulumi.Output<string>;
    /**
     * The AWS KMS key used to encrypt the secret (ID, Alias, or ARN)
     */
    declare public readonly kmsKeyId: pulumi.Output<string | undefined>;
    /**
     * An optional secret name transformer (e.g. DOPPLER_CONFIG in lower-kebab would be doppler-config). Valid transformers: none, camel, upper-camel, lower-snake, tf-var, dotnet, dotnet-env, lower-kebab
     */
    declare public readonly nameTransform: pulumi.Output<string | undefined>;
    /**
     * The path to the secret in AWS
     */
    declare public readonly path: pulumi.Output<string>;
    /**
     * The behavior to modify the provided path. Either `addDopplerSuffix` (default) which appends `doppler` to the provided path or `none` which leaves the path unchanged.
     */
    declare public readonly pathBehavior: pulumi.Output<string | undefined>;
    /**
     * The name of the Doppler project
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * The AWS region
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`). Defaults to `single-secret` if unspecified.
     */
    declare public readonly syncStrategy: pulumi.Output<string | undefined>;
    /**
     * AWS tags to attach to the secrets
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * If enabled, Doppler will update the AWS secret metadata (e.g. KMS key) during every sync. If disabled, Doppler will only set secret metadata for new AWS secrets.
     */
    declare public readonly updateMetadata: pulumi.Output<boolean | undefined>;
    /**
     * Behavior for AWS resource tags on updates (`never` update, `upsert` tags (leaving non-Doppler tags alone), `replace` tags (remove non-Doppler tags))
     */
    declare public readonly updateResourceTags: pulumi.Output<string | undefined>;

    /**
     * Create a SecretsSyncAwsSecretsManager resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretsSyncAwsSecretsManagerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretsSyncAwsSecretsManagerArgs | SecretsSyncAwsSecretsManagerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretsSyncAwsSecretsManagerState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["deleteBehavior"] = state?.deleteBehavior;
            resourceInputs["integration"] = state?.integration;
            resourceInputs["kmsKeyId"] = state?.kmsKeyId;
            resourceInputs["nameTransform"] = state?.nameTransform;
            resourceInputs["path"] = state?.path;
            resourceInputs["pathBehavior"] = state?.pathBehavior;
            resourceInputs["project"] = state?.project;
            resourceInputs["region"] = state?.region;
            resourceInputs["syncStrategy"] = state?.syncStrategy;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["updateMetadata"] = state?.updateMetadata;
            resourceInputs["updateResourceTags"] = state?.updateResourceTags;
        } else {
            const args = argsOrState as SecretsSyncAwsSecretsManagerArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.integration === undefined && !opts.urn) {
                throw new Error("Missing required property 'integration'");
            }
            if (args?.path === undefined && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["deleteBehavior"] = args?.deleteBehavior;
            resourceInputs["integration"] = args?.integration;
            resourceInputs["kmsKeyId"] = args?.kmsKeyId;
            resourceInputs["nameTransform"] = args?.nameTransform;
            resourceInputs["path"] = args?.path;
            resourceInputs["pathBehavior"] = args?.pathBehavior;
            resourceInputs["project"] = args?.project;
            resourceInputs["region"] = args?.region;
            resourceInputs["syncStrategy"] = args?.syncStrategy;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["updateMetadata"] = args?.updateMetadata;
            resourceInputs["updateResourceTags"] = args?.updateResourceTags;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretsSyncAwsSecretsManager.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SecretsSyncAwsSecretsManager resources.
 */
export interface SecretsSyncAwsSecretsManagerState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration?: pulumi.Input<string | undefined>;
    /**
     * The AWS KMS key used to encrypt the secret (ID, Alias, or ARN)
     */
    kmsKeyId?: pulumi.Input<string | undefined>;
    /**
     * An optional secret name transformer (e.g. DOPPLER_CONFIG in lower-kebab would be doppler-config). Valid transformers: none, camel, upper-camel, lower-snake, tf-var, dotnet, dotnet-env, lower-kebab
     */
    nameTransform?: pulumi.Input<string | undefined>;
    /**
     * The path to the secret in AWS
     */
    path?: pulumi.Input<string | undefined>;
    /**
     * The behavior to modify the provided path. Either `addDopplerSuffix` (default) which appends `doppler` to the provided path or `none` which leaves the path unchanged.
     */
    pathBehavior?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * The AWS region
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`). Defaults to `single-secret` if unspecified.
     */
    syncStrategy?: pulumi.Input<string | undefined>;
    /**
     * AWS tags to attach to the secrets
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * If enabled, Doppler will update the AWS secret metadata (e.g. KMS key) during every sync. If disabled, Doppler will only set secret metadata for new AWS secrets.
     */
    updateMetadata?: pulumi.Input<boolean | undefined>;
    /**
     * Behavior for AWS resource tags on updates (`never` update, `upsert` tags (leaving non-Doppler tags alone), `replace` tags (remove non-Doppler tags))
     */
    updateResourceTags?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SecretsSyncAwsSecretsManager resource.
 */
export interface SecretsSyncAwsSecretsManagerArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * The behavior to be performed on the secrets in the sync target when this resource is deleted or recreated. Either `leaveInTarget` (default) or `deleteFromTarget`.
     */
    deleteBehavior?: pulumi.Input<string | undefined>;
    /**
     * The slug of the integration to use for this sync
     */
    integration: pulumi.Input<string>;
    /**
     * The AWS KMS key used to encrypt the secret (ID, Alias, or ARN)
     */
    kmsKeyId?: pulumi.Input<string | undefined>;
    /**
     * An optional secret name transformer (e.g. DOPPLER_CONFIG in lower-kebab would be doppler-config). Valid transformers: none, camel, upper-camel, lower-snake, tf-var, dotnet, dotnet-env, lower-kebab
     */
    nameTransform?: pulumi.Input<string | undefined>;
    /**
     * The path to the secret in AWS
     */
    path: pulumi.Input<string>;
    /**
     * The behavior to modify the provided path. Either `addDopplerSuffix` (default) which appends `doppler` to the provided path or `none` which leaves the path unchanged.
     */
    pathBehavior?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project
     */
    project: pulumi.Input<string>;
    /**
     * The AWS region
     */
    region: pulumi.Input<string>;
    /**
     * Determines whether secrets are synced to a single secret (`single-secret`) as a JSON object or multiple discrete secrets (`multi-secret`). Defaults to `single-secret` if unspecified.
     */
    syncStrategy?: pulumi.Input<string | undefined>;
    /**
     * AWS tags to attach to the secrets
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * If enabled, Doppler will update the AWS secret metadata (e.g. KMS key) during every sync. If disabled, Doppler will only set secret metadata for new AWS secrets.
     */
    updateMetadata?: pulumi.Input<boolean | undefined>;
    /**
     * Behavior for AWS resource tags on updates (`never` update, `upsert` tags (leaving non-Doppler tags alone), `replace` tags (remove non-Doppler tags))
     */
    updateResourceTags?: pulumi.Input<string | undefined>;
}
