// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Doppler service account.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const ci = new doppler.ServiceAccount("ci", {
 *     name: "ci",
 *     workplaceRole: "collaborator",
 * });
 * ```
 *
 * ## Import
 *
 * import using the service account slug from the URL:
 * https://dashboard.doppler.com/workplace/[workplace-slug]/team/service_accounts/[service-account-slug]
 *
 * ```sh
 * $ pulumi import doppler:index/serviceAccount:ServiceAccount default <service-account-slug>
 * ```
 */
export class ServiceAccount extends pulumi.CustomResource {
    /**
     * Get an existing ServiceAccount resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceAccountState, opts?: pulumi.CustomResourceOptions): ServiceAccount {
        return new ServiceAccount(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/serviceAccount:ServiceAccount';

    /**
     * Returns true if the given object is an instance of ServiceAccount.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceAccount {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceAccount.__pulumiType;
    }

    /**
     * The name of the service account
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The slug of the service account
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;
    /**
     * A list of the workplace permissions for the service account (or use `workplaceRole`)
     */
    declare public readonly workplacePermissions: pulumi.Output<string[] | undefined>;
    /**
     * The identifier of the workplace role for the service account (or use `workplacePermissions`)
     */
    declare public readonly workplaceRole: pulumi.Output<string | undefined>;

    /**
     * Create a ServiceAccount resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ServiceAccountArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceAccountArgs | ServiceAccountState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceAccountState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["workplacePermissions"] = state?.workplacePermissions;
            resourceInputs["workplaceRole"] = state?.workplaceRole;
        } else {
            const args = argsOrState as ServiceAccountArgs | undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["workplacePermissions"] = args?.workplacePermissions;
            resourceInputs["workplaceRole"] = args?.workplaceRole;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceAccount.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceAccount resources.
 */
export interface ServiceAccountState {
    /**
     * The name of the service account
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The slug of the service account
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * A list of the workplace permissions for the service account (or use `workplaceRole`)
     */
    workplacePermissions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The identifier of the workplace role for the service account (or use `workplacePermissions`)
     */
    workplaceRole?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ServiceAccount resource.
 */
export interface ServiceAccountArgs {
    /**
     * The name of the service account
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A list of the workplace permissions for the service account (or use `workplaceRole`)
     */
    workplacePermissions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The identifier of the workplace role for the service account (or use `workplacePermissions`)
     */
    workplaceRole?: pulumi.Input<string | undefined>;
}
