// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manage a Doppler service account identity.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const ci = new doppler.ServiceAccount("ci", {
 *     name: "ci",
 *     workplaceRole: "collaborator",
 * });
 * const githubOidc = new doppler.ServiceAccountIdentity("github_oidc", {
 *     serviceAccountSlug: ci.slug,
 *     name: "GitHub Actions OIDC",
 *     ttlSeconds: 600,
 *     configOidc: {
 *         discoveryUrl: "https://token.actions.githubusercontent.com",
 *         claimsType: "wildcard",
 *         claims: [
 *             {
 *                 key: "aud",
 *                 values: ["https://github.com/DopplerHQ"],
 *             },
 *             {
 *                 key: "sub",
 *                 values: [
 *                     "repo:DopplerHQ/terraform-provider-doppler:pull_request",
 *                     "repo:DopplerHQ/terraform-provider-doppler:ref:refs/heads/feature*",
 *                 ],
 *             },
 *         ],
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import doppler:index/serviceAccountIdentity:ServiceAccountIdentity default <service-account-slug>.<service-account-identity-slug>
 * ```
 */
export class ServiceAccountIdentity extends pulumi.CustomResource {
    /**
     * Get an existing ServiceAccountIdentity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceAccountIdentityState, opts?: pulumi.CustomResourceOptions): ServiceAccountIdentity {
        return new ServiceAccountIdentity(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/serviceAccountIdentity:ServiceAccountIdentity';

    /**
     * Returns true if the given object is an instance of ServiceAccountIdentity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceAccountIdentity {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceAccountIdentity.__pulumiType;
    }

    /**
     * The OIDC configuration for the identity
     */
    declare public readonly configOidc: pulumi.Output<outputs.ServiceAccountIdentityConfigOidc>;
    /**
     * The display name of the service account identity
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Slug of the service account
     */
    declare public readonly serviceAccountSlug: pulumi.Output<string>;
    /**
     * Slug of the service account identity
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;
    /**
     * The amount of time, in seconds, that auth tokens for this identity will be valid
     */
    declare public readonly ttlSeconds: pulumi.Output<number>;

    /**
     * Create a ServiceAccountIdentity resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceAccountIdentityArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceAccountIdentityArgs | ServiceAccountIdentityState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceAccountIdentityState | undefined;
            resourceInputs["configOidc"] = state?.configOidc;
            resourceInputs["name"] = state?.name;
            resourceInputs["serviceAccountSlug"] = state?.serviceAccountSlug;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["ttlSeconds"] = state?.ttlSeconds;
        } else {
            const args = argsOrState as ServiceAccountIdentityArgs | undefined;
            if (args?.configOidc === undefined && !opts.urn) {
                throw new Error("Missing required property 'configOidc'");
            }
            if (args?.serviceAccountSlug === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceAccountSlug'");
            }
            if (args?.ttlSeconds === undefined && !opts.urn) {
                throw new Error("Missing required property 'ttlSeconds'");
            }
            resourceInputs["configOidc"] = args?.configOidc;
            resourceInputs["name"] = args?.name;
            resourceInputs["serviceAccountSlug"] = args?.serviceAccountSlug;
            resourceInputs["ttlSeconds"] = args?.ttlSeconds;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceAccountIdentity.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceAccountIdentity resources.
 */
export interface ServiceAccountIdentityState {
    /**
     * The OIDC configuration for the identity
     */
    configOidc?: pulumi.Input<inputs.ServiceAccountIdentityConfigOidc | undefined>;
    /**
     * The display name of the service account identity
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Slug of the service account
     */
    serviceAccountSlug?: pulumi.Input<string | undefined>;
    /**
     * Slug of the service account identity
     */
    slug?: pulumi.Input<string | undefined>;
    /**
     * The amount of time, in seconds, that auth tokens for this identity will be valid
     */
    ttlSeconds?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a ServiceAccountIdentity resource.
 */
export interface ServiceAccountIdentityArgs {
    /**
     * The OIDC configuration for the identity
     */
    configOidc: pulumi.Input<inputs.ServiceAccountIdentityConfigOidc>;
    /**
     * The display name of the service account identity
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Slug of the service account
     */
    serviceAccountSlug: pulumi.Input<string>;
    /**
     * The amount of time, in seconds, that auth tokens for this identity will be valid
     */
    ttlSeconds: pulumi.Input<number>;
}
