// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage the trusted IP allowlist for a Doppler config. Only requests from the specified IP ranges will be permitted to access the config's secrets via the API.
 *
 * Requires a **Team or Enterprise plan**. Collaborators and other project roles with the `enclaveProjectConfigTrustedIps` permission have permission to manage trusted ips for a config.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const backendPrd = new doppler.TrustedIps("backend_prd", {
 *     project: "backend",
 *     config: "prd",
 *     trustedIps: [
 *         "203.0.113.0/24",
 *         "198.51.100.5/32",
 *         "2001:db8::1/128",
 *     ],
 * });
 * const backendStg = new doppler.TrustedIps("backend_stg", {
 *     project: "backend",
 *     config: "stg",
 *     trustedIps: ["203.0.113.0/24"],
 * });
 * const backendDev = new doppler.TrustedIps("backend_dev", {
 *     project: "backend",
 *     config: "dev",
 *     trustedIps: ["0.0.0.0/0"],
 * });
 * ```
 *
 * ## Notes
 *
 * - **Warning:** Reconfiguring trusted IPs could lock you out of the config if the current client IP is not included in the trusted list.
 * - The default state for any config is `["0.0.0.0/0"]` (allow all traffic). Deleting this resource restores that default.
 * - Trusted IPs restrict API access only. They do not affect Dashboard logins.
 * - IP addresses must be specified in CIDR notation. Use `/32` for an exact IPv4 address and `/128` for an exact IPv6 address (e.g. `1.2.3.4/32` or `2001:db8::1/128`).
 *
 * ## Import
 *
 * An existing trusted IP configuration can be imported using `<project>.<config>`:
 *
 * ```sh
 * $ pulumi import doppler:index/trustedIps:TrustedIps backend_prd backend.prd
 * ```
 */
export class TrustedIps extends pulumi.CustomResource {
    /**
     * Get an existing TrustedIps resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TrustedIpsState, opts?: pulumi.CustomResourceOptions): TrustedIps {
        return new TrustedIps(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/trustedIps:TrustedIps';

    /**
     * Returns true if the given object is an instance of TrustedIps.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TrustedIps {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TrustedIps.__pulumiType;
    }

    /**
     * The name of the Doppler config
     */
    declare public readonly config: pulumi.Output<string>;
    /**
     * The name of the Doppler project where the config is located
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * List of trusted IP ranges in CIDR notation (e.g. 203.0.113.0/24, 1.2.3.4/32). Use 0.0.0.0/0 to allow all traffic.
     */
    declare public readonly trustedIps: pulumi.Output<string[]>;

    /**
     * Create a TrustedIps resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TrustedIpsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TrustedIpsArgs | TrustedIpsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TrustedIpsState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["project"] = state?.project;
            resourceInputs["trustedIps"] = state?.trustedIps;
        } else {
            const args = argsOrState as TrustedIpsArgs | undefined;
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.trustedIps === undefined && !opts.urn) {
                throw new Error("Missing required property 'trustedIps'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["project"] = args?.project;
            resourceInputs["trustedIps"] = args?.trustedIps;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TrustedIps.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering TrustedIps resources.
 */
export interface TrustedIpsState {
    /**
     * The name of the Doppler config
     */
    config?: pulumi.Input<string | undefined>;
    /**
     * The name of the Doppler project where the config is located
     */
    project?: pulumi.Input<string | undefined>;
    /**
     * List of trusted IP ranges in CIDR notation (e.g. 203.0.113.0/24, 1.2.3.4/32). Use 0.0.0.0/0 to allow all traffic.
     */
    trustedIps?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a TrustedIps resource.
 */
export interface TrustedIpsArgs {
    /**
     * The name of the Doppler config
     */
    config: pulumi.Input<string>;
    /**
     * The name of the Doppler project where the config is located
     */
    project: pulumi.Input<string>;
    /**
     * List of trusted IP ranges in CIDR notation (e.g. 203.0.113.0/24, 1.2.3.4/32). Use 0.0.0.0/0 to allow all traffic.
     */
    trustedIps: pulumi.Input<pulumi.Input<string>[]>;
}
