// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Doppler workplace_role.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as doppler from "@nellisauction/pulumi-doppler";
 *
 * const teamManager = new doppler.WorkplaceRole("team_manager", {
 *     name: "Team Manager",
 *     permissions: ["team_manage"],
 * });
 * ```
 *
 * ## Import
 *
 * ```sh
 * $ pulumi import doppler:index/workplaceRole:WorkplaceRole default <workplace-role-identifier>
 * ```
 */
export class WorkplaceRole extends pulumi.CustomResource {
    /**
     * Get an existing WorkplaceRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkplaceRoleState, opts?: pulumi.CustomResourceOptions): WorkplaceRole {
        return new WorkplaceRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'doppler:index/workplaceRole:WorkplaceRole';

    /**
     * Returns true if the given object is an instance of WorkplaceRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkplaceRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkplaceRole.__pulumiType;
    }

    /**
     * The role's unique identifier
     */
    declare public /*out*/ readonly identifier: pulumi.Output<string>;
    /**
     * Whether or not the role is custom (as opposed to Doppler built-in)
     */
    declare public /*out*/ readonly isCustomRole: pulumi.Output<boolean>;
    /**
     * The name of the Doppler workplace role
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * A list of [Doppler workplace permissions](https://docs.doppler.com/reference/workplace_roles-create)
     */
    declare public readonly permissions: pulumi.Output<string[]>;

    /**
     * Create a WorkplaceRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkplaceRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkplaceRoleArgs | WorkplaceRoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WorkplaceRoleState | undefined;
            resourceInputs["identifier"] = state?.identifier;
            resourceInputs["isCustomRole"] = state?.isCustomRole;
            resourceInputs["name"] = state?.name;
            resourceInputs["permissions"] = state?.permissions;
        } else {
            const args = argsOrState as WorkplaceRoleArgs | undefined;
            if (args?.permissions === undefined && !opts.urn) {
                throw new Error("Missing required property 'permissions'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["permissions"] = args?.permissions;
            resourceInputs["identifier"] = undefined /*out*/;
            resourceInputs["isCustomRole"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkplaceRole.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WorkplaceRole resources.
 */
export interface WorkplaceRoleState {
    /**
     * The role's unique identifier
     */
    identifier?: pulumi.Input<string | undefined>;
    /**
     * Whether or not the role is custom (as opposed to Doppler built-in)
     */
    isCustomRole?: pulumi.Input<boolean | undefined>;
    /**
     * The name of the Doppler workplace role
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A list of [Doppler workplace permissions](https://docs.doppler.com/reference/workplace_roles-create)
     */
    permissions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a WorkplaceRole resource.
 */
export interface WorkplaceRoleArgs {
    /**
     * The name of the Doppler workplace role
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * A list of [Doppler workplace permissions](https://docs.doppler.com/reference/workplace_roles-create)
     */
    permissions: pulumi.Input<pulumi.Input<string>[]>;
}
